### PR TITLE
Create automated app screenshots - Risk calculation screen(EXPOSUREAPP-2996)

### PR DESCRIPTION
**Pull request by mtwalli**
Add screenshot tests for Risk calculation

### Testing:

1. run `./gradlew clean assembleDebug assembleAndroidTest` for clean state
2. run  `bundle exec fastlane screengrab`

### CODE REVIEW

**Comment by jurajkusnier** [comment]
I would also add a suffix to screenshot names, maybe cherry-pick commit c189160cb07d3f3ca9f2fe371da9c4b5186a0bf3 to make it possible to test on emulators with older android version. Besides that, it looks good.

**Review by jurajkusnier — APPROVED** [review]
LGTM, just don't forget to solve TODO in `TracingDetailsFragmnetTest` before merging.

**Comment by chris-cwa** [comment]
```
...$ bundle exec fastlane screenbrab
[✔] 🚀 
[14:33:09]: ------------------------------
[14:33:09]: --- Step: default_platform ---
[14:33:09]: ------------------------------
+------------------+---------+
|        Lane Context        |
+------------------+---------+
| DEFAULT_PLATFORM | android |
+------------------+---------+
[14:33:09]: Could not find lane 'android screenbrab'. Available lanes: android test, android beta, android deploy

+------+------------------+-------------+
|           fastlane summary            |
+------+------------------+-------------+
| Step | Action           | Time (in s) |
+------+------------------+-------------+
| 1    | default_platform | 0           |
+------+------------------+-------------+

[14:33:09]: fastlane finished with errors

[!] Could not find lane 'android screenbrab'. Available lanes: android test, android beta, android deploy
```
What am I doing wrong here?

**Review by chris-cwa — APPROVED** [review]
When running it the second time it works like a charm!
👍

**Pull request merged**
