### PR TITLE
Update UTC time to LocalTime (EXPOSUREAPP-1863)

### PR DESCRIPTION
**Pull request by SamuraiKek**
## Checklist

* [x] Test your changes as thoroughly as possible before you commit them. Preferably, automate your test by unit/integration tests.
* [x] If this PR comes from a fork, please [Allow edits from maintainers](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)
* [x] Set a speaking title. Format: {task_name} (closes #{issue_number}). For example: Use logger (closes # 41)
* [ ] [Link your Pull Request to an issue](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) - Pull Requests that are not linked to an issue with you as an assignee will be closed, except for minor fixes for typos or grammar mistakes in *documentation or code comments*.
* [ ] Create Work In Progress [WIP] pull requests only if you need clarification or an explicit review before you can continue your work item.
* [x] Make sure that your PR is not introducing _unnecessary_ reformatting (e.g., introduced by on-save hooks in your IDE)
* [x] Make sure that your PR does not contain changes in text files, therefore the PR must not contain changes in values/strings/* and / or assets/* (see issue #332 for further information)
* [x] Make sure that your PR does not contain compiled sources (already set by the default .gitignore) and / or binary files

## Description

Changed the way our API quota is calculated based on the updated requirements from Google from using UTC to using the phone's local time

### CODE REVIEW

**Comment by kbobrowski** [comment]
This will introduce exceeded quota error on devices which still use GMS version which resets quota at midnight UTC. Implementation should support both mechanisms until all devices have GMS version which resets quota at midnight local time. This pull request could be one way of implementing it: https://github.com/corona-warn-app/cwa-app-android/pull/931

**Comment by kbobrowski** [comment]
by the way, it would be great if you could also reference existing github issues in pull requests (in this case https://github.com/corona-warn-app/cwa-app-android/issues/912), not only internal jira, would be much easier for the community to keep track of actions around the issues (I found this pull request just by accident), thanks!

**Comment by SamuraiKek** [comment]
Hey @kbobrowski, from my understanding, it seems that the quota has always been calculated with device local time. I think there was a communication error with the guys from google and it was assumed that UTC would be used. Looking in the ENF documentation right now, it looks like it's been updated to clearly state that local time is used for both versions of the API.
CounterReset

**Comment by kbobrowski** [comment]
Hi @SamuraiKek , I'm quite sure that limit on calls was set to zero at midnight UTC, the implementation of CWA actually was assuming local time in the past, which was leading to 39508 and was fixed by https://github.com/corona-warn-app/cwa-app-android/pull/818 .

Looking at the source code of GMS, version 20.30.19, it seems that currently it still defines internally "day" as midnight to midnight UTC, when it comes to setting the limit to zero. Relevant part of the code:

```smali
 120     invoke-static {}, Ljava/lang/System;->currentTimeMillis()J
 121 
 122     move-result-wide v11
 127 
 129     sget-object v14, Ljava/util/concurrent/TimeUnit;->HOURS:Ljava/util/concurrent/TimeUnit;
 133 
 134     const-wide/16 v7, 0x18
 135 
 137     invoke-virtual {v14, v7, v8}, Ljava/util/concurrent/TimeUnit;->toMillis(J)J
 138 
 139     move-result-wide v7
 140 
 141     div-long/2addr v11, v7
```

And loose translation of limit reset mechanism to java:

```java
public class Quota {

  private long day = 0;
  private int count = 0;

  public void updateCount() {
    long currentDay = System.currentTimeMillis() / TimeUnit.HOURS.toMillis(24);
    if (currentDay > day) {
      day = currentDay;
      count = 0;
    }
    if (count < 20) {
      count += 1;
    }
  }

  public boolean canCallProvideDiagnosisKeys() {
    return count < 20;
  }
}
```

I think that change from UTC to local time is upcoming, non-documented breaking change that will be introduced with future version of GMS.

If you have rooted android device you can have a look at the place where it keeps track of the number of calls, in:

`/data/data/com.google.android.gms/files/nearby/shared`

**Comment by SamuraiKek** [comment]
Thanks @kbobrowski! It looks like you're right. We will try to clarify this with the team at Google before we take further action.

**Review by harambasicluka — APPROVED** [review]

**Pull request merged**
