### PR TITLE
Local seven day incidence (EXPOSUREAPP-9449)

### PR DESCRIPTION
**Pull request by SamuraiKek**
The local statistics card now includes the local hospitalization stats.

- Currently testable on mock-cloud. 
- When selecting an administrative unit the text at the bottom "Hospitalisierungen in" should be followed by the name of the state the administrative unit belongs to. So for ex: When Selecting "Potsdam", the state should be "Brandenburg".

### CODE REVIEW

**Review by NataliaLemmerth — DISMISSED** [review]
UA approved

**Review by AlexanderAlferov — DISMISSED** [review]
LGTM 🚀

**Review by AlexanderAlferov — APPROVED** [review]

**Review by chiljamgossow — APPROVED** [review]
LGTM

**Review by NataliaLemmerth — APPROVED** [review]
UA approved

**Pull request merged**
