### PR TITLE
Upgrade klint plugin (Dev)

### PR DESCRIPTION
**Pull request by mtwalli**
- Upgrade Klint plugins to latest versions to enjoy Koltin 1.4 features such as:
   - Trailing commas 
   - Kotlin SAM functions 

- Format the code 
- Fix klint unexpected indentation error in `DiagnosisTestResultRetrievalPeriodicWorker`

## Testing
built `deviceForTestersDebug` and `deviceForTestersRelease` and ran them on Samsung S8 - Android 9

Please checkout and test yourself

### CODE REVIEW

**Review by ralfgehrer — COMMENTED** [review]
Successfully tested on Pixel (Android 10) and Huawei P10 (Android 9)

**Review by ralfgehrer — APPROVED** [review]

**Review by BMItr — APPROVED** [review]
lgtm! tested on Nexus5x (Android 8)

**Review by LukasLechnerDev — APPROVED** [review]
LGTM! Tested on Samsung S20+ and Google Pixel 3A, both Android 11

**Review by jurajkusnier — APPROVED** [review]
Everything works well.
Tested on Pixel 4 (Android 11), OnePlus X (Android 6.0.1)

**Pull request merged**
