### PR TITLE
Hide keyboard on CJ note editing when day view is closed (EXPOSUREAPP-5887)

### PR DESCRIPTION
**Pull request by ralfgehrer**
**Steps:**
- create person or location
- on the day view edit the note for day or location
- during edit, leave the day view by pressing back in top-left corner

**Expected result:**
- the keyboard gets dismissed

### CODE REVIEW

**Review by harambasicluka — APPROVED** [review]
Works as expected 🚀 

OnePlus 8 Pro (Android 11)

**Review by kolyaopahle — APPROVED** [review]
also worked on my pixel 5 👍

**Comment by vaubaehn** [comment]
Hi,
@ralfgehrer explicitly triggered the open keyboard by pressing top-left back.
Did you check whether the fix also works, when you finished editing the note, and then change the focus to a different person or location by marking/activating the object? In my opinion the keyboard should also be closed in these cases (which is not the case in 1.15.x)

Also, when you test this, you might be able to trigger our good old friend 9002: activate/select person or location, tap into note field, press del on keyboard, unselect person/location. Please leave me a note whether you can reproduce 9002 npe, or if i should create an issue for this.

Cheers and good night,
V.

**Comment by ralfgehrer** [comment]
Many thanks for the feedback @vaubaehn. 
I'll tackle this as part of #2703 then.

**Comment by ralfgehrer** [comment]
Hi @vaubaehn, I addressed the issue in this PR: https://github.com/corona-warn-app/cwa-app-android/pull/2715

**Comment by vaubaehn** [comment]
Hi @ralfgehrer , thanks a lot for taking care and for giving information.
I'm wishing nice Easter Holidays to you and all the Dev-Team!

**Pull request merged**
