### PR TITLE
Error message after positive test result (EXPOSUREAPP-4515)

### PR DESCRIPTION
**Pull request by mtwalli**
Fix improper message in cases where:
🛠️   Tan can not be retrieved.
🛠️  Keys submission can be done.

In those two cases `BadRequestException` is wrapped into `TanPairingException`  that offers an insightful message to the end the user.

Unfortunately nothing can be done from the App side ,but to offer the end user a proper message. 
This was the case before somehow this message got lost due to some code refactoring.

### Testing
Keep trying the same follow a few times.
⚠️ *MAKE SURE* to reset the App to clear cached data.

device-2021-01-20-000424 device-2021-01-20-000440

### CODE REVIEW

**Comment by LukasLechnerDev** [comment]
Code looks good! Is it somehow possible to test this?

**Comment by mtwalli** [comment]
> Code looks good! Is it somehow possible to test this?

Yes, you should try to submit positive test result many times , at some point error will be shown. Please after each submission reset the App and try again.

**Review by LukasLechnerDev — APPROVED** [review]

**Review by chris-cwa — APPROVED** [review]
LGTM!

**Comment by MikeMcC399** [comment]
Link to #2035.

**Pull request merged**
