### PR TITLE
Test registration date remains from deleted test after adding a new test (EXPOSUREAPP-4484)

### PR DESCRIPTION
**Pull request by jurajkusnier**
I wasn't able to reproduce the bug so this is just an attempt to fix it or mitigate the effects

### CODE REVIEW

**Comment by d4rken** [comment]
Can you further elaborate on where you think the issue is and how this mitigates it?

**Comment by d4rken** [comment]
Hm, that would mean the bug happens if the user registers a second test but the CWA has never left RAM (no low memory, no reboots) since the first test?

Then the bug would be with the second test never updating the timestamp though :thinking: 

I don't like that we make the date nullable further done the line in UI related classes. It's not good to allow this value to be nullable if the UI elements make no sense if it is null.

**Comment by d4rken** [comment]
This doesn't fix the underlying cause: The second test didn't update the timestamp
It would hide the symptoms: The first removed test sets the date to null, the second never updates it, the test date would be displayed as "today" and most users wouldn't notice it unless they see that the date keeps showing "today" and the keep looking at it after 24h again.

I would prefer to not hide the symptoms as it's not a fix and will make it more difficult to spot and debug this issue, and eventually come up with an actual fix. In case this was somehow related to encrypted preferences, this might already be fixed in 1.15.x too.

**Comment by jurajkusnier** [comment]
> Hm, that would mean the bug happens if the user registers a second test but the CWA has never left RAM (no low memory, no reboots) since the first test?
> 
> Then the bug would be with the second test never updating the timestamp though 🤔
> 
> I don't like that we make the date nullable further done the line in UI related classes. It's not good to allow this value to be nullable if the UI elements make no sense if it is null.

From the bug description, it could be possible that the date is just in memory as the user deleted the test just before entering another test and the test result came in a few hours.
Date was actually always nullable, was changed to not nullable just recently. Also clearing nullable dates doesn't seem right when it always must have some value.

**Comment by jurajkusnier** [comment]
> This doesn't fix the underlying cause: The second test didn't update the timestamp
> It would hide the symptoms: The first removed test sets the date to null, the second never updates it, the test date would be displayed as "today" and most users wouldn't notice it unless they see that the date keeps showing "today" and the keep looking at it after 24h again.
> 
> I would prefer to not hide the symptoms as it's not a fix and will make it more difficult to spot and debug this issue, and eventually come up with an actual fix. In case this was somehow related to encrypted preferences, this might already be fixed in 1.15.x too.

Yes, it was another assumption that it could be related to encrypted preferences, but without logs, it's hard to predict where the issue could be.

**Comment by harambasicluka** [comment]
As we don't exactly know where the problem is it won't go into 1.1.-0, if we are able to implement a reliable fix we'll ship it with 2.0.x.

**Pull request closed without merging**
