### PR TITLE
DGC related Testresult-UI dynamics (EXPOSUREAPP-7427)

### PR DESCRIPTION
**Pull request by BMItr**
This PR addresses Exposureapp-7427.
BulletPoints in TestresultView should adjust content dynamically depending on PCR/RAT/Cert supported..
Please check the Overall-Ticket or Figma(best way) for all possible routes.

How-To-Test (examples):
- PCR Test with Example QR Code 
- Check the Pending testresult Screen

image
(should contain bottom point)

- Scan RAT Test with Example QR Code
- Check the pending testresult Screen

image
(should contain bottom point)

Note: if the overall implementation is ready, and if the isAdvancedGiven attribute is set, "By your wish, no test cert ..." should be shown. (Consent will come with other PR/Subtask)

### CODE REVIEW

**Review by ChristinaTsigganos — DISMISSED** [review]
UA approved

**Review by jurajkusnier — DISMISSED** [review]
LGTM

**Review by axelherbstreith — APPROVED** [review]
Looks good 👍   Tested on Samsung S8

**Review by jurajkusnier — APPROVED** [review]

**Review by ChristinaTsigganos — APPROVED** [review]
UA approved

**Pull request merged**
