### PR TITLE
Add app shortcut for contact diary (EXPOSUREAPP-4659) (closes #2130)

### LINKED ISSUE #2130: Contact diary: Add Android launcher shortcut
* [y] This enhancement request has not already been raised before
* [y] Enhancement request is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)
* [y] If you are proposing a new feature, please do so in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)

## Current Implementation
Open contact diary by opening app, scrolling down and pressing on contact diary button. (3 Actions)

## Suggested Enhancement
Add Android launcher shortcut (long press on app in launcher) for contact diary view. (2 Actions)

## Expected Benefits
Users avoid going into the app and scrolling down and again click on contact diary. They can also open contact diary with one long and one short press. Also users will be able to detach the shortcut into a full grown app icon and thus reducing the necessary UI actions to only 1 or 2 actions. (1 Action if current launcher supports detaching 

Better UX and lower UI interaction count will (hopefully) lead to higher acceptance. 

---
Internal Tracking ID: [EXPOSUREAPP-4659](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4659)

### PR DESCRIPTION
**Pull request by PhilippNowak96**
### Description

As written in #2130 an app shortcut for the contact diary could improve the user experience quickly navigating there. This PR adds such a shortcut. The `Intent` of the shortcut points to the `LauncherActivity` to make sure the existing flow does not get broken. I modified the conditions a little bit but all in all it should be similar like before:

1. Check, if an update is needed and possibly show the update dialog
2. Check, if the user is not onboarded yet and possibly show the onboard dialog
3. Otherwise fire the renamed event `GoToAppShortcutOrMainActivity` which will tell the `LauncherActivity` to evaluate if an app shortcut should be opened or we finally open the `MainActivity` based on the intent extras.

### Screenshots

Long press on app launcher icon:

2130-homescreen

After clicking the contact diary shortcut:

2130-after-shortcut

### How to test

- Long press on app launcher icon
- Select `Kontakt-Tagebuch` (or `Kontakt-Tagebuch öffnen` if long description is shown)

### TODOs

- Please check `shortcutShortLabel` and `shortcutLongLabel`, especially their translations. I'm not familiar with how your translation system works and how to trigger a needed translation from the team. I added german strings (they need to be checked too) as well as strings for the default but with empty content.
- I used the `ic_diary_book` for the icon. The android documentation says app shortcut icons should be 24x24dp which is not the case for the used image. It seems to work but should definitely be changed with a smaller icon.
- Due to the flow described above there is an edge case: When the user wasn't onboarded yet, the onboarding flow will be shown and afterwards the `MainActivity`. I'm not sure if this is a problem from a UX perspective. If yes we could maybe disable the shortcut and enable it after the user was onboarded.

Feel free to tackle any of this todos or ping me with the provided information and I will do so 😄

---
Internal Tracking ID: [EXPOSUREAPP-4659](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4659)

### CODE REVIEW

**Comment by dsarkar** [comment]
Internal Tracking ID: [EXPOSUREAPP-4659](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4659)

**Comment by harambasicluka** [comment]
@PhilippNowak96 to give you a short heads up, discussions going on, but it looks like that we'll include it somehow in our next sprint.

**Comment by harambasicluka** [comment]
@PhilippNowak96 we got the GO to work on this feature! As we have our internal requirements we can't use your PR as it is, @jurajkusnier will try to reuse as much as possible. We'll let you know when the PR is up and we would really like to get your feedback on this!! 🚀 

Thanks for your patience
Luka 😄

**Comment by PhilippNowak96** [comment]
@harambasicluka Hey Luka,

nice to hear this will be continued! :) It's really fine fine for me to close this PR if it's easier to develop it internally. I'm looking forward to see the results and provide some feedback.

**Comment by harambasicluka** [comment]
Hi, as already announced we are working directly on a shortcut implementation. For this I'll close this PR, please add your feedback here: https://github.com/corona-warn-app/cwa-app-android/pull/2384

Thanks! :)

**Pull request closed without merging**
