### PR TITLE
Adjust Info Screen to announce new Release-Features for 2.21 (EXPOSUREAPP-12249)

### PR DESCRIPTION
**Pull request by SamuraiKek**
[Ticket](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12249)

### CODE REVIEW

**Review by KathrinLuecke — DISMISSED** [review]
UA approved

**Review by marcauberer — DISMISSED** [review]

**Comment by SamuraiKek** [comment]
There might be another bulletpoint added to the new release screen so pls no merging for now...

**Comment by SamuraiKek** [comment]
Alright, ready to be merged.

**Review by mtwalli — APPROVED** [review]

**Review by BMItr — APPROVED** [review]

**Review by KathrinLuecke — APPROVED** [review]
UA approved

**Pull request merged**
