### PR TITLE
Enhance screenshots (EXPOSUREAPP-5250)

### PR DESCRIPTION
**Pull request by mtwalli**
- Increase time delay to avoid blank screenshots
-  Support DE and EN only 
- Run screenshot on every commit (To be removed, just for verifying it works on Circle Ci)
Ticket: https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5250

### Testing
Run screenshots full session on your machine 📸 

### TODO
Run full test

### CODE REVIEW

**Comment by harambasicluka** [comment]
This PR is used to test the new config, can be merged if screenshots on CircleCi look fine.

**Comment by harambasicluka** [comment]
Still very flaky. Should we increase the timeout even further?

**Comment by mtwalli** [comment]
Could be closed in favour of https://github.com/corona-warn-app/cwa-app-android/pull/2426

**Comment by harambasicluka** [comment]
https://github.com/corona-warn-app/cwa-app-android/pull/2426

**Pull request closed without merging**
