### PR TITLE
Adjust automated screenshots - add low risk card without encounters (EXPOSUREAPP-4837)

### PR DESCRIPTION
**Pull request by LukasLechnerDev**
This PR adds the low-risk card in the state without encounters to our suite of screenshots:

image

Although a bit out of scope, as discussed with @mtwalli, I also refactored the code that takes a screenshot of the FAQ card. 

If you only want to generate screenshots for the HomeScreen and only in German, you can adapt your `Screengrabfile` locally to:

```
locales ['de-DE']
use_adb_root true
clear_previous_screenshots true
app_package_name 'de.rki.coronawarnapp.test'
launch_arguments ["annotation testhelpers.Screenshot"]
test_instrumentation_runner 'testhelpers.TestApplicationUIRunner'
app_apk_path Dir.glob('**/build/outputs/apk/deviceForTesters/debug/*.apk').first
tests_apk_path Dir.glob('**/build/outputs/apk/androidTest/deviceForTesters/debug/*.apk').first
use_tests_in_classes ['de.rki.coronawarnapp.ui.main.MainActivityTest']

### CODE REVIEW

**Review by mtwalli — APPROVED** [review]
LGTM

**Review by ralfgehrer — COMMENTED** [review]
LGTM - currently running fastlane

**Comment by ralfgehrer** [comment]
I ran it on a Pixel (Android 10) and noticed that the risk card properties are empty on all languages

Screenshot 2021-02-05 at 13 48 30
Screenshot 2021-02-05 at 13 48 37

**Comment by LukasLechnerDev** [comment]
@ralfgehrer I ran the screenshot tests again, but the risk cards looked fine on my Samsung S20+. 

I think this issues might have nothing to with this specific PR, but with the screenshot tests themselves?

@mtwalli Could it be that on some devices the screenshots are taken before the data is actually bound to the UI? I can remember that we once had a `delay` before actually taking a screenshot. As far as I can see we don't have it anymore. Was it there in order to fix issues as the one @ralfgehrer has here?

**Comment by mtwalli** [comment]
> @ralfgehrer I ran the screenshot tests again, but the risk cards looked fine on my Samsung S20+.
> 
> I think this issues might have nothing to with this specific PR, but with the screenshot tests themselves?
> 
> @mtwalli Could it be that on some devices the screenshots are taken before the data is actually bound to the UI? I can remember that we once had a `delay` before actually taking a screenshot. As far as I can see we don't have it anymore. Was it there in order to fix issues as the one @ralfgehrer has here?

Delay still there, I just moved into `takeScreenshot` inline function. To have it in one place and no need to add it to every unit test.

Screenshot 2021-02-05 at 16 10 26

I'm running them now on S8.
@ralfgehrer  could you please check if you have animations disabled on your device or not?

**Comment by mtwalli** [comment]
I confirm it works fine. I just ran a full session 

Screenshot 2021-02-05 at 17 49 56

**Comment by ralfgehrer** [comment]
@mtwalli animations are off. Will try with another device.

**Review by ralfgehrer — APPROVED** [review]

**Pull request merged**
