### PR TITLE
7 day r value decimal place issue (EXPOSUREAPP-4751)

### PR DESCRIPTION
**Pull request by LukasLechnerDev**
Number formatting issue. "0.00" was cut off.

### CODE REVIEW

**Review by jurajkusnier — CHANGES_REQUESTED** [review]
We would have the same issue for other decimal places. For example, if you add this line 
`Arguments.of(1.0, 3, Locale.GERMANY, "1,000")`
to `StatisticsNumberValueFormatterTest` test will fail too

**Comment by LukasLechnerDev** [comment]
@jurajkusnier Thanks for your input. I made a change that fixes this issue. However, we have the same issue when the decimal value is >3 but I don't think that the API will return such decimals.

**Comment by jurajkusnier** [comment]
> @jurajkusnier Thanks for your input. I made a change that fixes this issue. However, we have the same issue when the decimal value is >3 but I don't think that the API will return such decimals.

ok, let is like this for now

**Review by jurajkusnier — DISMISSED** [review]

**Review by chiljamgossow — CHANGES_REQUESTED** [review]
The number leading the separator is gone now, just displaying ,95

**Comment by LukasLechnerDev** [comment]
@chiljamgossow Great that you spotted that! I fixed it.

**Review by jurajkusnier — APPROVED** [review]

**Review by ralfgehrer — APPROVED** [review]

**Pull request merged**
