### PR TITLE
Cannot delete tests older than 21 days - DE: Tests die älter als 21 Tage sind, können nicht gelöscht werden (EXPOSUREAPP-2398)

### PR DESCRIPTION
**Pull request by kolyaopahle**
### Description
The original pr #1481 did not fix the actual issue people were having in production.

This PR implements a refactoring of the whole state handling process for test result fetching and should hopefully get rid of the actual underlying issue.

### Steps to reproduce
With Emulator:
1. Setup CWA Server emulation
2. Try to scan a qr code
3. Try refetching the testresult in many places and with different results (note that all test results other than pending require a relaunch of the app to be refetched)

To test the specific 21 days failure case you need to do the following:
1. Setup CWA Server emulation
2. Scan a qr code
3. set status as pending in server emulator
4. return to homescreen
5. set status as 400 error in server emulator
6. check if fetching or error card appears on homescreen

Without emulator
1. Get QR codes for your testing environment from Sharepoint
2. Scan the qr codes and test if test behaviour is consistent

### CODE REVIEW

**Review by chris-cwa — APPROVED** [review]
ran it without emulator. worked fine.

**Comment by harambasicluka** [comment]
Tested it together with https://github.com/corona-warn-app/cwa-app-android/pull/1600 . Works as expected, will review the coding.

**Comment by BMItter** [comment]
code lgtm. running device tests with different fetches.. will come back later

**Review by BMItr — APPROVED** [review]
Code looks good to me. Local Tests passed.
Tested various conditions on emulated QRs on WRU-XD
Default Test: local tests passed, 
pending QR: passed
invalid QR: passed
negativ QR: passed
positiv QR: passed

UI updates accordingly.
Note: I will contact you on one smaller issue.
Approved.

**Pull request merged**
