### PR TITLE
Center certificates vertically (EXPOSUREAPP-13667)

### PR DESCRIPTION
**Pull request by schauersbergern**
[Ticket](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13667)

Testing:
Send exported certificate per mail
Follow steps 3-6 found in ticket in the section "On Desktop"

### CODE REVIEW

**Comment by MikeMcC399** [comment]
- This PR resolves https://github.com/corona-warn-app/cwa-app-android/issues/5369

**Review by SamuraiKek — APPROVED** [review]
Looks alright. I didn't have adobe installed so I used [this website](https://www.pdftron.com/pdf-tools/pdf-measurement/) to measure the distance.

**Review by mtwalli — APPROVED** [review]

**Comment by mtwalli** [comment]
@MikeMcC399  will you be able to verify the fix provided here yourself?

**Comment by MikeMcC399** [comment]
@mtwalli 

> will you be able to verify the fix provided here yourself?

I measured an exported German 1/2 vaccination certificate and the cross was correctly centered.

**Pull request merged**
