### PR TITLE
Increase key retrieval worker launch interval to hourly (EXPOSUREAPP-3455)

### PR DESCRIPTION
**Pull request by d4rken**
The worker for periodic key retrieval and submission should launch every hour, since we now download the hourly key packages.

The other changes remove the unnecessary indirection for determining the launch interval, and add a test that actually checks the created worker request instead of the constants.

### CODE REVIEW

**Review by harambasicluka — APPROVED** [review]
Can't really test background workers, app is working as expected.

**Comment by AlexanderAlferov** [comment]
Code looks nice. Testing on device.

**Review by AlexanderAlferov — APPROVED** [review]
Tested on device with not allowed background prio - looks good.

**Comment by BMItter** [comment]
please wait with merging some minutes (sent one question to d4ken about potential issue..)

**Comment by BMItter** [comment]
all right, did not reach him yet. Feel free to merge,
Code looks good.

**Review by BMItr — APPROVED** [review]

**Comment by vaubaehn** [comment]
@d4rken 
Hi Matthias, hope you're fine.
If you find 2 minutes, could you have a quick check at #1691, if hourly fetching DKs will mitigate/fix #1691 from 1.7.0 on?
Kind greetings, v.

**Pull request merged**
