### PR TITLE
Move creation of notification channel to app startup (closes #27)

### LINKED ISSUE #27: Create Notification Channel On App Start
## Current Implementation
Currently the notification channel gets created, as soon as a notification is raised.

## Suggested Enhancement
Create the notification channel on app startup.
## Expected Benefits
If the notification channel is setup on app startup, then the user is able to see what types of notifications the app will post. In addition, the user can directly modify the settings based on personal preference. This would not be possible, if the notification channel was not created, because there was no notification yet. This could lead to incomprehensible bevhavior of the app in the eyes of the user.

We would be happy, if we could supply a PR 😁 

Best Regards 🚀 
Robert Jakobs & Tim Brüggenthies (@timbrueggenthies)

### PR DESCRIPTION
**Pull request by timbrueggenthies**
Fixes #27 

Best Regards
Tim Brüggenthies & Robert Jakobs (@Magoli1)

### CODE REVIEW

**Review by jakobmoellerdev — COMMENTED** [review]
This looks good from my side. 👍 I will do a manual test tomorrow.

**Review by harambasicluka — COMMENTED** [review]
Also looks fine from my side, thx :)

**Comment by timbrueggenthies** [comment]
Perfect! I could rebase now to resolve conflicts if desirable.

**Comment by jakobmoellersap** [comment]
Please Rebase, then I approve and it gets to the next dev to master 👍

**Comment by timbrueggenthies** [comment]
There you go!

**Review by jakobmoellerdev — APPROVED** [review]

**Pull request merged**
