### PR TITLE
Add option to clear text fields when adding/editing persons/locations (DEV)

### PR DESCRIPTION
**Pull request by d4rken**
The text fields on iOS had the "clear text" option while we don't, can't let :green_apple: :100: us.

* Add `app:endIconMode="clear_text"` to person/location add/edit text fields.
* Shorten overly long layout ids

Screenshot from 2021-02-24 13-31-29

### CODE REVIEW

**Review by axelherbstreith — APPROVED** [review]
LGTM 👍 Tested on Samsung Galaxy S8 (Android 10)

**Review by kolyaopahle — APPROVED** [review]
LGTM 👍

**Comment by mtwalli** [comment]
Tested on Samsung S8 Android 9, it flickers sometimes.

**Comment by mtwalli** [comment]
https://user-images.githubusercontent.com/25054729/109007359-548e5a80-76ac-11eb-9bd2-57cc09a39447.mp4

**Pull request merged**
