### PR TITLE
Partially untranslated screenshot of PersonOverviewFragment (EXPOSUREAPP-11996)

### PR DESCRIPTION
**Pull request by marcauberer**
Addresses [EXPOSUREAPP-11996](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11996).

### CODE REVIEW

**Review by mtwalli — APPROVED** [review]
Thx!

**Review by BMItr — APPROVED** [review]
lgtm!  👌 thx @marcauberer

**Comment by marcauberer** [comment]
@BMItr @mtwalli Could one of you set the internal ticket to complete please? I currently have no access to Jira. Thanks

**Comment by mtwalli** [comment]
> @BMItr @mtwalli Could one of you set the internal ticket to complete please? I currently have no access to Jira. Thanks

done

**Pull request merged**
