### PR TITLE
Printing option (EXPOSUREAPP-5675)

### PR DESCRIPTION
**Pull request by mtwalli**
Support printing options as in design 
Screenshot 2021-03-11 at 09 31 07

https://user-images.githubusercontent.com/25054729/110758960-6136b500-824d-11eb-9040-445ba7979545.mp4

### CODE REVIEW

**Review by AlexanderAlferov — APPROVED** [review]
LGTM. Tested on Samsung S8. 
Screenshot 2021-03-11 at 12 20 33

**Review by BMItr — COMMENTED** [review]
tested on pixel 2 (Android 11), working fine.
@mtwalli could you check lower android versions?
I made a quick test on Android 8.1 without success...

**Comment by mtwalli** [comment]
> tested on pixel 2 (Android 11), working fine.
> @mtwalli could you check lower android versions?
> I made a quick test on Android 8.1 without success...

Did you get an error ? crash ? or ?

**Comment by BMItter** [comment]
> > tested on pixel 2 (Android 11), working fine.
> > @mtwalli could you check lower android versions?
> > I made a quick test on Android 8.1 without success...
> 
> Did you get an error ? crash ? or ?

printing / Pdf mode was just not showing up

**Review by BMItr — APPROVED** [review]
with latest commits, now working on older devices.
Test successful for Pixel 2, Nexus 5x, Huawei P20.
code lgtm

**Pull request merged**
