### PR TITLE
Organizer Flow: Add Onboarding Screen to Menu (DEV)

### PR DESCRIPTION
**Pull request by axelherbstreith**
Small PR that links the onboarding screen to the QR code list fragment menu

To test it: Access the "Sie planen eine Veranstaltung" Card. Then open the "Information" Button on the Menu. Check if the navigation is working fine

### CODE REVIEW

**Review by AlexanderAlferov — APPROVED** [review]

**Comment by SamuraiKek** [comment]
The transition between the "My QR-Codes" screen and the info screen is kinda weird. There's a second where the two layouts look merged before the info screen shows up fully. I was actually able to take a screenshot of this so it's pretty noticeable.
Screenshot_20210414-124206

**Review by harambasicluka — CHANGES_REQUESTED** [review]
Yes, spotted the same problem as @SamuraiKek.

https://user-images.githubusercontent.com/64483219/113277074-adbb6080-92e0-11eb-8118-cd4ffe207da6.mp4

**Comment by axelherbstreith** [comment]
@SamuraiKek @harambasicluka yes I noticed that too. This seems to be an issue with the TraceLocation List Fragment. All interactions started from this fragment cause this "delay" 


E.g.: When duplicating a TraceLocation or navigating to the QR code detail screen: 
 

https://user-images.githubusercontent.com/75120552/113277539-228e9a80-92e1-11eb-90d0-d3d9fdb7ba0c.mp4

Would suggest to put the fix in a different PR

**Review by harambasicluka — APPROVED** [review]
Let's get this in and try to fix the problem with the list.

**Pull request merged**
