### PR TITLE
Typo correction in the JavaDoc

### PR DESCRIPTION
**Pull request by vg-scylla**
Just a small correction in the JavaDoc of the ConnectivityHelper class.

## Checklist

* [ ] Test your changes as thoroughly as possible before you commit them. Preferably, automate your test by unit/integration tests.
* [ ] If this PR comes from a fork, please [Allow edits from maintainers](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)
* [ ] Set a speaking title. Format: {task_name} (closes #{issue_number}). For example: Use logger (closes # 41)
* [ ] [Link your Pull Request to an issue](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) - Pull Requests that are not linked to an issue with you as an assignee will be closed, except for minor fixes for typos or grammar mistakes in *documentation or code comments*.
* [ ] Create Work In Progress [WIP] pull requests only if you need clarification or an explicit review before you can continue your work item.
* [ ] Make sure that your PR is not introducing _unnecessary_ reformatting (e.g., introduced by on-save hooks in your IDE)
* [ ] Make sure that your PR does not contain changes in text files, therefore the PR must not contain changes in values/strings/* and / or assets/* (see issue #332 for further information)
* [ ] Make sure that your PR does not contain compiled sources (already set by the default .gitignore) and / or binary files

### CODE REVIEW

**Comment by jakobmoellersap** [comment]
Hey apparently after switching base to dev, some stuff from the comments went wrong. Could you kindly recheck before we merge?

**Comment by vg-scylla** [comment]
Checked: the typo ist still there. It says register instead of unregister in the ConnectivityHelper class Bluetooth unregister method.

**Comment by jakobmoellersap** [comment]
I was suggesting that you remove the diff and do the line change for the typo again so we do not have 60 line changes. Or are these intended?

**Comment by vg-scylla** [comment]
I opened a new pull request in the actual code. Hope this is What you meant? Sorry for the inconveniences

**Pull request closed without merging**
