### PR TITLE
Update event_registration_strings.xml (COMMUNITY)

### PR DESCRIPTION
**Pull request by FirephoenixX02**
Fixed Typeos
Btw: Just testing not a real Improvement to the App. But if I created this Pull Request right ill do some more later.

### CODE REVIEW

**Comment by DerVogel2020** [comment]
Should be changed on the website and iOS as well.

**Comment by FirephoenixX02** [comment]
> Should be changed on the website and iOS as well.

**Comment by FirephoenixX02** [comment]
The Closing and Reopening wasn't planned accidentally clicked the button -,-

**Comment by harambasicluka** [comment]
@FirephoenixX02 thanks for your first contribution 🚀  
We work with release branches for development. So please target `release/2.2.x`.

**Comment by d4rken** [comment]
We want to include YOUR commit, so you are part of the CWA's history, but to get off on the right foot, please read the PR template.

Minimum:
* Have a corresponding issue ticket
* Target the next release (would be `release/2.2.x`)

There is is still time till end of next week,  so if you have time,  let's do that and include your commit!
I would :heart: to include your actual commit. I really dislike making the same change, just on my commit, due to processes, but this is a huge project with a few processes :wink:.

Please reopen once the concerns are addressed, or open a new PR.

**Comment by d4rken** [comment]
Merged community PRs as example: https://github.com/corona-warn-app/cwa-app-android/pulls?q=is%3Apr+label%3Acommunity+++is%3Amerged

**Comment by dsarkar** [comment]
Hi @FirephoenixX02, Thanks for contributing to the project. See the comments above from the developer team, please. Best wishes, DS 


---
Corona-Warn-App Open Source Team

**Comment by FirephoenixX02** [comment]
> We want to include YOUR commit, so you are part of the CWA's history, but to get off on the right foot, please read the PR template.
> 
> Minimum:
> 
>     * Have a corresponding issue ticket
> 
>     * Target the next release (would be `release/2.2.x`)
> 
> 
> There is is still time till end of next week, so if you have time, let's do that and include your commit!
> I would heart to include your actual commit. I really dislike making the same change, just on my commit, due to processes, but this is a huge project with a few processes wink.
> 
> Please reopen once the concerns are addressed, or open a new PR.

I'll try next time but im fairly new to Github and also Android App Development.
But thank you for the great feedback ;D

**Pull request closed without merging**
