### PR TITLE
Add (missing) arrow icon to create RAT profile card (closes #3162)

### LINKED ISSUE #3162: Missing arrow icon on creating rapid-test profile
## Avoid duplicates
* [x] This enhancement request has not already been raised before
* [x] Enhancement request is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)
* [x] If you are proposing a new feature, please do so in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)

## Current Implementation

The screen to register tests is composed of multiple profile cards that redirect to subsequent screens. To indicate the subsequent screens, arrow icons are used on all cards, except on the card to create the RAT profile.

## Suggested Enhancement

Add the arrow icon to the card for the creation of the RAT profile. See #3161

## Expected Benefits

¯\_(ツ)_/¯

----
Internal Tracking-ID: [EXPOSUREAPP-7269](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7269)

### PR DESCRIPTION
**Pull request by kechtel**
### Description

See issue #3162

The screen to register tests is composed of multiple profile cards that redirect to subsequent screens. To indicate the subsequent screens, arrow icons are used on all cards, except on the card to create the RAT profile. This PR addresses this issue by adding the arrow icon to the respective card.

### Steps to reproduce

1. Open CWA
2. On the main screen on the card "Register your test" select "Next steps".
3. On the screen "Register your test" see the arrow icon on the card "Create Rapid Test Profile".

----
Internal Tracking-ID: [EXPOSUREAPP-7269](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7269)

### CODE REVIEW

**Comment by mtwalli** [comment]
Thanks for the PR , but the arrow is not missing. it is done as per design specs

**Comment by kechtel** [comment]
> Thanks for the PR , but the arrow is not missing. it is done as per design specs

@mtwalli Thanks for your quick response! If the design specs do not contain the arrow, this PR is superfluous. However, I am confused, since the arrow seems to be present in the iOS version of the app (see e.g. https://github.com/corona-warn-app/cwa-app-ios/pull/2559).

**Comment by d4rken** [comment]
Keen eye @kechtel :wink: 

Mohammed is right that this is implemented according to our design specs, the "create" card has no arrow, while the "existing" card has one.

I agree though that this seems inconsistent in regards to iOS and we will clarify with the designers whether this was intentional or an oversight.

**Comment by MikeMcC399** [comment]
@d4rken 
> we will clarify with the designers whether this was intentional or an oversight.

That is good to hear!

There is a reference screenshot from iOS on https://www.coronawarn.app/assets/img/screenshots/en/ios/iPhone%2011%20Pro-tan_submissionflow_qr_0002.png which shows the right angle-brackets used on the iOS screens to indicate a deeper level that can be accessed by tapping on each tile.

image

**Comment by MikeMcC399** [comment]
Under Android 2.2.1, once a Rapid Test Profile has been created, the tile "Rapid Test Profile" shows a right-arrow. I can't think of any good reason why the "Create Rapid Test Profile" should not have an arrow, whilst the "Rapid Test Profile" does not have an arrow.

**Comment by d4rken** [comment]
The arrow should be there. 
We've clarified and it was an oversight in the reference designs (no error on dev sight :yum:). 
Thanks @kechtel .

**Review by d4rken — APPROVED** [review]
lgtm, I fixed the padding.

Did you actually test the layout change on your device @kechtel ?

Before my commit:
Screenshot from 2021-05-17 13-11-52

After:
Screenshot from 2021-05-17 13-10-09

**Comment by kechtel** [comment]
@d4rken Thank you for clarifying with the designers and fixing the padding! I have to admit that I only tested the changes using Android Studio's Design Tools and did not test them on my device. That might be the reason why I did not notice the issue with the padding.

**Review by mtwalli — APPROVED** [review]

**Pull request merged**
