### PR TITLE
Text changes positive test result (EXPOSUREAPP-11128)

### PR DESCRIPTION
**Pull request by jurajkusnier**
### Testing
- Add Positive PCR/RAT test
- Compare screens with design in Figma
- Focus only on highlighted parts, the rest (button & text labels) is not defined right now

### Jira Link
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11128

### CODE REVIEW

**Review by CV113 — DISMISSED** [review]
UA approved

**Review by chiljamgossow — APPROVED** [review]
LGTM
Tested with RAT and PCR

**Review by AlexanderAlferov — APPROVED** [review]
LGTM 🚀

**Review by CV113 — APPROVED** [review]
UA approved

**Pull request merged**
