### PR TITLE
Checkin - Adjusted international timeformat (EXPOSUREAPP-6467)

### PR DESCRIPTION
**Pull request by BMItr**
This PR addresses EXPOSUREAPP-6467 (MY Check-Ins: wrong time format)

Expected result:
_Check in time is displayed correctly
As OS language is English, the time Format should be shown appropriately --> max 12 hours & AM or PM"_ 

Before result:
_Check in time is shown as follows "2$s" --> No matter what check in time has been selected
German time format (um to 24 hours), although OS language is English_

Screenshot / HotToTest
- Just create an event and check the displayed times with different os languages.

image

### CODE REVIEW

**Review by harambasicluka — DISMISSED** [review]
Your fix works for the "My QR Code"  screen, but the same problem still exists on the "My Checkins" screen:
image

**Review by axelherbstreith — DISMISSED** [review]

**Review by AlexanderAlferov — DISMISSED** [review]
LGTM 🚀 
PS: I could confirm Luka's comment about formatting in attendee qr code list.

**Comment by BMItter** [comment]
@harambasicluka @AlexanderAlferov 
of course it is handled in the other screen to!
https://github.com/corona-warn-app/cwa-app-android/pull/2890
have a look 👀  ;-)

**Comment by BMItter** [comment]
> LGTM 🚀
> PS: I could confirm Luka's comment about formatting in attendee qr code list.
implemented ;-) (was not mentioned in the ticket)

**Review by harambasicluka — APPROVED** [review]
🎉  thanks :)

**Review by axelherbstreith — APPROVED** [review]

**Pull request merged**
