### PR TITLE
[Feature branch] boofCV scanner (EXPOSUREAPP-10502)

### PR DESCRIPTION
**Pull request by mtwalli**
- Replaces Zxing scanner with boofCV scanner 
- Focus on:
        - Autofocus pre Android 8 devices
        - Scan Different QrCodes (RC, TC, VC, PCR, RAT)
        - Build an RC and see that Lombok is not bundled in the APK (inspect the APK in Android Studio)

## Ticket
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10502

### CODE REVIEW

**Comment by vaubaehn** [comment]
@mtwalli @thomasaugsten 
While boofCV will enhance the situation for many people having problems to scan their QR codes, there is one remarkable downside:
CovPass is also using boofCV, and users with Samsung Flip foldable phones report that app crashes when trying to scan a QR code. So, CWA is their best option to carry their digital certificate.

After the switch to boofCV in CWA we will see many angry Samsung users...
Is there any way to mitigate the issue? Or is there a plan how to handle that likely upcoming situation?

**Comment by mtwalli** [comment]
@vaubaehn  Thanks for pointing this out. We have it in mind and we are in contact CovPass team already to address these issues. 

See https://github.com/corona-warn-app/cwa-app-android/pull/4590/files#diff-d8e4db221d9680b9bb32944bac81191e0753c6ac990b35e530b50299f9a9585cR110-R111

**Comment by vaubaehn** [comment]
@mtwalli 
Great, thanks. Some CovPass users will be happy after it's fixed there.
Despite all advantages, using ProGuard sometimes looks like walking through a minefield...

A good and healthy start into 2022 to you and your team!

**Comment by LukasLechnerDev** [comment]
I have tested it now with my 2 devices (Google Pixel 3A and 4A) and experienced some problems

Pixel 4A:
- Scanning the first certificate works fine, but all subsequent scanning attemps fail; if I restart the app, again only the first scan is successful

Pixel 3A: 
- First scan sometimes works
- Experienced some crashes on subsequent scanning attempts

Please let me know if you need further information (logs, etc)

**Comment by mtwalli** [comment]
@LukasLechnerDev  Please share the logs?

**Comment by SamuraiKek** [comment]
Tested on Samsung Galaxy S10+. Scanning seems to work alright. It's an improvement over zxing but, I still get the occasional hang were I need to do some voodoo to get the QR to be scanned. 

I also built an APK and I actually saw `lombok` is bundled inside.

**Comment by mtwalli** [comment]
> 



> Tested on Samsung Galaxy S10+. Scanning seems to work alright. It's an improvement over zxing but, I still get the occasional hang were I need to do some voodoo to get the QR to be scanned.
> 
> I also built an APK and I actually saw `lombok` is bundled inside.

As discussed , Please pull the latest changes and try again?

**Comment by LukasLechnerDev** [comment]
> @LukasLechnerDev Please share the logs?
[CWA Log 2022-01-03 11_43_33.800.txt](https://github.com/corona-warn-app/cwa-app-android/files/7801491/CWA.Log.2022-01-03.11_43_33.800.txt)

Here is the log from the crash on my Pixel 3A

**Review by jurajkusnier — COMMENTED** [review]
I was able to crash the app. I'm not sure if it's the same issue as @LukasLechnerDev  reported or something new. Crash is caused by:

```
2022-01-03 15:23:40.396 21346-21346/de.rki.coronawarnapp.test E/main: Uncaught exception!
    java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.Display.getRotation()' on a null object reference
        at de.rki.coronawarnapp.qrcode.ui.QrCodeScannerPreviewView.bindUseCases(QrCodeScannerPreviewView.kt:100)
        at de.rki.coronawarnapp.qrcode.ui.QrCodeScannerPreviewView.setupCamera$lambda-0(QrCodeScannerPreviewView.kt:63)
        at de.rki.coronawarnapp.qrcode.ui.QrCodeScannerPreviewView.$r8$lambda$fm2mndOdx9RaiESnswczqPcInPQ(QrCodeScannerPreviewView.kt)
        at de.rki.coronawarnapp.qrcode.ui.QrCodeScannerPreviewView$$ExternalSyntheticLambda1.run(Unknown Source)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5461)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
```

**Review by LukasLechnerDev — APPROVED** [review]
LGTM! Made some tests with different QR codes and the scanner worked really quick and reliable. No crashes anymore. Good work!

**Review by BMItr — APPROVED** [review]
finally, lgtm!

**Pull request merged**
