### PR TITLE
Move booster rules to files dir (EXPOSUREAPP-13503)

### LINKED ISSUE #5557: Twitter Report: Booster recommendation push notification is sent every day
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Samsung A3 (2016)
- Android version: 7.0
- App version: 2.26.0

## Describe the bug

The CWA sends a push notification reminding the user of the booster recommendation every day instead of just once.

## Steps to reproduce the issue

Not really clear when this happens.

## Expected behaviour

The app should only send one push notification and not one every day.

## Additional context

I asked the user to create an error log. 

## Internal Ticket 
[EXPOSUREAPP-13503
](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13503
)

### PR DESCRIPTION
**Pull request by chiljamgossow**
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13503

Booster rules trigger notifications if a change is detected, so they should be kept in a permanent storage to ensure consistency.

For backward compatibility, the cache directory is checked as a fallback.

How to test: Deleting the cache from Android settings, installing this branch or a ccl update should have no impact on booster notifications. You can also check the files on the device.

### CODE REVIEW

**Comment by Ein-Tim** [comment]
- Is this related to https://github.com/corona-warn-app/cwa-app-android/issues/5557? Will it fix that issue?

**Comment by mtwalli** [comment]
> * Is this related to [Twitter Report: Booster recommendation push notification is sent every day #5557](https://github.com/corona-warn-app/cwa-app-android/issues/5557)? Will it fix that issue?

@Ein-Tim  Yes, can you ask the user if her/his device run into low storage, or have some App that clear the cache?

**Comment by chiljamgossow** [comment]
> * Is this related to [Twitter Report: Booster recommendation push notification is sent every day #5557](https://github.com/corona-warn-app/cwa-app-android/issues/5557)? Will it fix that issue?

This is my best explanation for the reported behaviour and the error report we received. I could also reproduce the behaviour by clearing the app's cache from Android settings.

**Review by mtwalli — APPROVED** [review]

**Comment by Ein-Tim** [comment]
@mtwalli 

Confirmed, user has low free storage and caches are cleared regularly.

**Pull request merged**
