### PR TITLE
Translation Delivery (DEV)

### PR DESCRIPTION
**Pull request by service-tip-git**
Translation Delivery

### CODE REVIEW

**Comment by service-tip-git** [comment]
This pull request is for translation delivery. Please review and approve them.

**Comment by harambasicluka** [comment]
This was a test, the other languages will come later today.

**Comment by harambasicluka** [comment]
values-en has to be deleted after this PR get merged.

**Review by axelherbstreith — DISMISSED** [review]

**Comment by service-tip-git** [comment]
This pull request is for translation delivery. Please review and approve them.

**Review by harambasicluka — APPROVED** [review]

**Review by axelherbstreith — APPROVED** [review]

**Pull request merged**
