### PR TITLE
Automatically refresh certificates after DSC list update (EXPOSUREAPP-8886)

### PR DESCRIPTION
**Pull request by jurajkusnier**
### Testing
- install CWA 2.6
- generate and scan tc, vc, rc
- update CWA with this branch
- check if all certificates are still valid
- you can also play with the Test Menu ( DCC Signature Verification > Refresh / Clear cache )

### CODE REVIEW

**Review by mtwalli — APPROVED** [review]
Lgtm, did not check on device

**Comment by SamuraiKek** [comment]
Tested on device from 2.6 to this branch with the certificate from the jira ticket but it still shows up invalid for me.

**Comment by mtwalli** [comment]
@SamuraiKek  Please double check , I have tested the same scenario on device and it worked

**Comment by SamuraiKek** [comment]
> @SamuraiKek Please double check , I have tested the same scenario on device and it worked

Retested again. It was a connection issue with my Samsung. After restarting the phone it worked.

**Review by SamuraiKek — APPROVED** [review]

**Pull request merged**
