### PR TITLE
Contact Journal Day date is not announced (EXPOSUREAPP-4457)

### PR DESCRIPTION
**Pull request by axelherbstreith**
**This PR was closed since the target base was changed from 1.12 to 1.11. New PR is: #2146**

Small PR to adjust the TalkBack behavior when opening the contact journal day screen - removed announcement of unneeded information.

In addition, I added the text "Day View" or "Tagesansicht" which is announces directly after the current date when opening the day screen. This allows to better understand on which view you are currently located.

device-2021-01-18-115415

To test the changes, activate TalkBack on your device and navigate to the contact journal day screen.

### CODE REVIEW

**Review by ralfgehrer — CHANGES_REQUESTED** [review]
Tested on Pixel (Android  10)

**Review by ralfgehrer — DISMISSED** [review]

**Review by chiljamgossow — DISMISSED** [review]

**Comment by ralfgehrer** [comment]
As discussed, please switch the target branch to 1.11.

**Review by ralfgehrer — CHANGES_REQUESTED** [review]
Unfortunately, you need to rebase the branch and cannot simply change the target branch- otherwise you will introduce unwanted changes of 1.12. to 1.11.

**Review by janetback — DISMISSED** [review]
UA reviewed

**Pull request closed without merging**
