### PR TITLE
Fix cut title in certificates info screen (EXPOSUREAPP-10175)

### PR DESCRIPTION
**Pull request by SamuraiKek**
[Ticket](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10175)

Title in certain languages was too long and it was getting cut. Switch to English to test.

### CODE REVIEW

**Review by LukasLechnerDev — APPROVED** [review]
👍 Title not cut off anymore

**Comment by MikeMcC399** [comment]
Verified with repro steps from issue https://github.com/corona-warn-app/cwa-app-android/issues/4202 on Android 11.

## Steps

On Pixel 3a emulator:

1. Settings > Display > Font size > Default
2. Settings > Display > Display size > Default
3. Language English (United States)

In Android Studio:

1. Run `CovPassInfoFragmentTest.kt`
2. View file `/data/data/de.rki.coronawarnapp.test/screenshots/CovPassInfoFragment.png` with Device File Explorer
3. Note title is no longer truncated and it wraps onto two lines

CovPassInfoFragment_Top_half

**Comment by MikeMcC399** [comment]
There is still an issue on this screen with wide devices, such as new folding ones, described in 
- https://github.com/corona-warn-app/cwa-app-android/issues/4203

If you are making changes to the layout `fragment_cov_pass_info.xml`, this may be a good time to also take a look at this other issue.

**Review by mtwalli — APPROVED** [review]

**Comment by mtwalli** [comment]
> There is still an issue on this screen with wide devices, such as new folding ones, described in
> 
>     * ["Certificate Verification by Third Parties" image overlaps title #4203](https://github.com/corona-warn-app/cwa-app-android/issues/4203)
> 
> 
> If you are making changes to the layout `fragment_cov_pass_info.xml`, this may be a good time to also take a look at this other issue.

@we have a separate ticket for this issue

**Pull request merged**
