### PR TITLE
Fix scrolling for SubmissionQRCodeInfoFragment (EXPOSUREAPP-3436) (closes #1607)

### LINKED ISSUE #1607: "Dokument mit QR-Code" screen not scrollable
## Describe the bug

Lower text on QR code screen not readable because it's off bounds
Screenshot

## Expected behaviour

Scrolling works

## Steps to reproduce the issue

1. "Informieren und Helfen"
2. "Weiter"
3. "Dokument mit QR-Code"
4. "Erlauben"
5. Try to scroll

## Technical details

- Mobile device: Huawei P10
- Android version: 9

---
Internal Tracking ID:  EXPOSUREAPP-3436

### PR DESCRIPTION
**Pull request by PhilippNowak96**
### Description

Some text on the SubmissionQRCodeInfo Fragment was hidden by the action button. There was already a ScrollView but it did not get constraint against the button and therefore it was unscrollable.

#### Old behaviour

old

#### New behaviour

new

In addition I did a little refactoring (extract the ScrollView part into an extra layout file) to match the other layouts like SubmissionContactFragment and did some smaller adjustments to _match_parent_ sizes in ConstraintLayout (which are not allowed even though they still work).

### Steps to reproduce

1. Setup a small emulator (e.g. Nexus 5)
2. Go to "Learn more and help" -> Next -> Document with QR code -> Accept

### CODE REVIEW

**Comment by chris-cwa** [comment]
Could I ask you to set the target branch to release/1.8.x, not main branch, please?

**Comment by PhilippNowak96** [comment]
Ah yes of course :) Done.

**Comment by PhilippNowak96** [comment]
@chris-cwa By the way, maybe it's worth mentioning that the topmost ImageView in this screen has no content description. Due to the request of not changing any localization stuff I did not further touch this part.

**Review by d4rken — APPROVED** [review]
lgtm

**Review by kolyaopahle — APPROVED** [review]
LGTM 👍

**Pull request merged**
