### PR TITLE
Fix:  Reminder-Notification (EXPOSUREAPP-12685)

### PR DESCRIPTION
**Pull request by jurajkusnier**
Use `testIdentifier` in the reminder notification

### Testing
- Scan positive PCR/RAT test and get results
- don't warn others
- wait until you see reminder notification with text "Bitte warnen Sie andere und teilen Sie Ihr Testergebnis"
- tap on the notification and you should be able to complete the submission flow

**Testing tip:** notification is scheduled for 2h after the test result has been received but you can decrease waiting time by playing with values of the `POSITIVE_RESULT_NOTIFICATION_INITIAL_OFFSET` and `POSITIVE_RESULT_NOTIFICATION_INTERVAL` in your local branch.

### Jira Ticket
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12685

### CODE REVIEW

**Comment by mtwalli** [comment]
@schauersbergern can you please review this PR ?

**Review by SamuraiKek — APPROVED** [review]
Works. Reduced the waiting time on my local branch to 1 minute as you suggested.

**Review by schauersbergern — APPROVED** [review]
Looks good, also worked with my tests

**Comment by BMItr** [comment]
image
👌

**Review by BMItr — APPROVED** [review]

**Pull request merged**
