### PR TITLE
Difficulty dismissing UQS scanner pop-up (EXPOSUREAPP-12295, EXPOSUREAPP-10623)

### LINKED ISSUE #4400: UQS pop up is shown on top of other screens
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Huawei P Smart 2019
- Android version: 10
- App version: 2.13.3

## Describe the bug

The UQS pop up is shown on top of other screens, here are some examples: 

## Steps to reproduce the issue

1. Delete and reinstall the app
2. Do not dismiss the pop up
3. Create a QR code on https://www.coronawarn.app/en/eventregistration/ and scan it with an external QR code scanner
4. Enter the app following the link
5. See the issue which is shown in the first screenshot above
6. Try the same with RA test result QR codes

## Expected behaviour

The pop up should not be shown if the app is not displaying the normal screens ("Status", "Certificates", "Check-in" or "Jounal").

---
Internal Tracking ID: [EXPOSUREAPP-10623](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10623)

### LINKED ISSUE #4940: Difficulty dismissing UQS scanner pop-up
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Google Pixel 3a emulator
- Android version: 12
- App version: 2.19.0 (also pre-[release/2.20.x](https://github.com/corona-warn-app/cwa-app-android/tree/release/2.20.x))

## Describe the bug

The Universal QR code Scanner (UQS) button displays a pop-up after app installation to inform new users about its capabilities. Other pop-ups displayed during on-boarding prevent dismissing the UQS pop-up until they have been dismissed causing a sub-optimal user experience.

## Steps to reproduce the issue

Set font size to "Small"

1. Clean install of Corona-Warn-App
2. Tap "LET'S GET STARTED"
3. Tap "NEXT"
4. Tap "DO NOT ACTIVATE" and confirm
5. Tap "NEXT", tap "NEXT"
6. Tap "DO NOT SHARE"
7. Tap on X of QR Code Scanner pop-up and note that nothing happens

QR code scanner pop-up

9. Dismiss other pop-ups (OK), (DO NOT ALLOW) & (OK)
10. Tap again on X of QR Code Scanner pop-up and note that this time the pop-up is dismissed

## Expected behavior

If the QR Code Scanner pop-up is shown with an X to dismiss it, then it should always be possible to dismiss the pop-up by tapping on the X.

## Possible Fix

Remove the pop-up from being displayed. Users no longer need to be specially informed about this function which was introduced several versions ago.

## Additional context

The Universal QR code Scanner (UQS) was introduced in October 2021 with CWA version 2.12. See blog post [Corona-Warn-App version 2.12 enables central access to QR code scanner and expands statistics area](https://www.coronawarn.app/en/blog/2021-10-19-cwa-version-2-12/). This is now 5 months ago.

- Issue https://github.com/corona-warn-app/cwa-app-android/issues/4400 also concerns a problem with the UQS pop-up which would be solved by removing it.

---
Internal Tracking ID: [EXPOSUREAPP-12295](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12295)

### PR DESCRIPTION
**Pull request by mtwalli**
- Align tooltip style 
- Increase closing area 
[Ticket](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12295), [Ticket 2](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10623)

### CODE REVIEW

**Comment by Ein-Tim** [comment]
This would be a good chance to also fix https://github.com/corona-warn-app/cwa-app-android/issues/4400.

**Review by KathrinLuecke — DISMISSED** [review]
UA approved

**Comment by MikeMcC399** [comment]
@mtwalli 

- The changes do not resolve the issue described in #4940 and the following steps to reproduce still show the problem occurring:

## Steps to reproduce

- Device name: Google Pixel 3a emulator
- Android version: 12

Set font size to "Small"

1. Clean install of Corona-Warn-App
2. Tap "Let's Get Started"
3. Tap "Next"
4. Tap "Do Not Activate" and confirm
5. Tap "Next", tap "Next"
6. Tap "Do Not Share"
7. Tap on X of QR Code Scanner pop-up and note that nothing happens
8. Dismiss other pop-ups (OK), (Do Not Allow) & (OK)
9. Tap again on X of QR Code Scanner pop-up and note that this time the pop-up is dismissed

## Suggestion

Perhaps the UQS scanner pop-up display could be delayed until the other pop-ups from onboarding have all been dealt with? That would get around the issue that the UQS scanner pop-up does not react when tapped if any of the onboarding pop-ups are still displayed.

**Comment by mtwalli** [comment]
> @mtwalli And what about fixing #4400?

there is another ticket for that

**Comment by Ein-Tim** [comment]
@mtwalli Wich is open for more than half a year without anything happening. But ok, your call...

**Comment by MikeMcC399** [comment]
@mtwalli 

> you can not dismiss the tooltip or click anything on the screen if any other popup is still showing up, this is an expected behaviour. Simply because other tooltip view does not have the focus yet. you can not click on the bottom bar too

Is there something which can be done to improve the user experience to not display the tooltip if this view can't take focus?

I also made the alternative suggestion to remove this tooltip completely to simplify the user interface. The scan button isn't new any more and probably doesn't need any special introduction any longer.

**Comment by mtwalli** [comment]
@MikeMcC399  As per alignment with UX , Tooltip won't show up anymore on fresh install

> > @mtwalli
> > > you can not dismiss the tooltip or click anything on the screen if any other popup is still showing up, this is an expected behaviour. Simply because other tooltip view does not have the focus yet. you can not click on the bottom bar too
> > 
> > 
> > Is there something which can be done to improve the user experience to not display the tooltip if this view can't take focus?
> > I also made the alternative suggestion to remove this tooltip completely to simplify the user interface. The scan button isn't new any more and probably doesn't need any special introduction any longer.
> 
> I will take it to the UX team to see if they can offer different solution

@MikeMcC399 As per alignment with UX, tooltip will not show up on fresh install, but with app update if not shown before ,I guess with the change the issue you mentioned will be resolved

**Comment by MikeMcC399** [comment]
@mtwalli 

Sounds good! Thank you!

**Comment by mtwalli** [comment]
> @mtwalli
> 
> Sounds good! Thank you!

@MikeMcC399 , you can check again now
- Tooltip won't show up on fresh install
- Upgrade to new version (change Minor number in gradle.properties)
- Tooltip will show up (if not shown before)
- Dismiss the tooltip
- Upgrade to a newer version than in step two 
- Tooltip won't anymore

**Comment by MikeMcC399** [comment]
@mtwalli

The change you listed:

> * Tooltip won't show up on fresh install

is sufficient to solve issue https://github.com/corona-warn-app/cwa-app-android/issues/4940 from my point of view. 

I checked it out and it looks good! 👍🏻

**Review by SamuraiKek — APPROVED** [review]

**Pull request merged**
