### PR TITLE
Privacy policy not displayed correctly on old devices (EXPOSUREAPP-7268)

### PR DESCRIPTION
**Pull request by mtwalli**
Please make sure that all App Information sub screens are working as before + on Android 6 have right formatting

## Ticket
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7268

close https://github.com/corona-warn-app/cwa-app-android/issues/3166

### CODE REVIEW

**Comment by MikeMcC399** [comment]
This PR causes some longer URLs not to be completely displayed any more.

On Android 8, using 2.25.0 and selecting App Information > Data Privacy then URLs are fully visible. See especially the URLs in Section 7:

Android 8 2 25

With this PR, the URLs still work as hyperlinks however they are truncated when displayed:

Android 8 issue with fix

**Comment by mtwalli** [comment]
> This PR causes some longer URLs not to be completely displayed any more.
> 
> On Android 8, using 2.25.0 and selecting App Information > Data Privacy, then URLs are fully visible. See especially the URLs in Section 7:
> 
> Android 8 2 25
> 
> With this PR, the URLs still work as hyperlinks however they are truncated when displayed:
> 
> Android 8 issue with fix
> 
> (Same problem on Android 6 and 12.)

@MikeMcC399  it is not truncated, you just need to scroll to the right. I will try to make content fit in the screen width.

**Comment by MikeMcC399** [comment]
@mtwalli 

> it is not truncated, you just need to scroll to the right. 

You are right. Since there is no scroll-bar shown, I didn't think of trying to scroll to the right.

> I will try to make content fit in the screen width.

Thank you!

I noticed two other unwanted side-effects of this change on Android 8:

1. When the privacy document is shown during onboarding, it displays as literal HTML text instead of being interpreted as HTML.
2. Links in the Terms of Use (App Information > Terms of Use) are no longer clickable.

**Comment by mtwalli** [comment]
Looks like using WebView comes with other issues ,despite text should be in HTML format , it appears to have some formatting issues. Closing this PR in favour of https://github.com/corona-warn-app/cwa-app-android/pull/5502

**Pull request closed without merging**
