### PR TITLE
Restrict number of persons (EXPOSUREAPP-10613)

### PR DESCRIPTION
**Pull request by mtwalli**
## Test against LOCAL mock server (`Max=5 ,threshold=2`)
- Scan certificates for different persons
- When threshold is `numberOfDistinctPersons + 1` > `threshold` -> warning should appear with every new person added 
   - Certificate is still imported 
- When `numberOfDistinctPersons` >=  `Max ` Block dialog should appear 
   - Certificate is NOT imported 

### Ticket
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10613

### CODE REVIEW

**Comment by Ein-Tim** [comment]
Hi @mtwalli 

Could you elaborate a bit what is planned here?

Thank you!

**Comment by mtwalli** [comment]
@Ein-Tim  The idea is to restrict the number of persons to whom certificates can imported in the App. To avoid importing certificates when it is not intended (such as Validating certificates using CWA) in this case user will be warned to use CovPassCheck for that and if the number exceeds the maximum allowance importing new certificates will be blocked

**Comment by Ein-Tim** [comment]
@mtwalli

Thanks for the answer! This makes sense!

**Review by AlexanderAlferov — APPROVED** [review]

**Review by chiljamgossow — APPROVED** [review]

**Review by KathrinLuecke — COMMENTED** [review]
UA approved

**Comment by chstdu** [comment]
It would be even better than fixed thresholds to use an additional "Do Not Import" flag in the QR code to prevent accidentally importing certificates "again". This was already proposed on the CWA wishlist months ago: https://github.com/corona-warn-app/cwa-wishlist/issues/601

**Comment by Ein-Tim** [comment]
@mtwalli JFYI: I'm still waiting for it :D

**Pull request merged**
