### PR TITLE
Release screen 3.1 (EXPOSUREAPP-14607)

### PR DESCRIPTION
**Pull request by mtwalli**
[Ticket](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14607)

### CODE REVIEW

**Review by schauersbergern — APPROVED** [review]

**Comment by Ein-Tim** [comment]
So will the app still show the new features screen, but it's empty or what will the user see after the update?

**Review by KathrinLuecke — APPROVED** [review]
UA approved

**Comment by KathrinLuecke** [comment]
@Ein-Tim The usual sentence "Mit diesem Update stellen wir Ihnen neben Fehlerbehebungen auch neue und erweiterte Funktionen zur Verfügung." + list of features will be skipped. Instead the sentence "Mit diesem Update beheben wir Fehler in der App. Es enthält keine neuen Funktionen." will be displayed.

**Comment by Ein-Tim** [comment]
I still think this makes no sense, but we had this discussion already, so that's fine for me! (:

**Pull request merged**
