### PR TITLE
Translation Delivery (DEV)

### PR DESCRIPTION
**Pull request by service-tip-git**
Translation Delivery

### CODE REVIEW

**Comment by service-tip-git** [comment]
This pull request is for translation delivery. Please review and approve them.

**Review by mtwalli — DISMISSED** [review]

**Comment by mtwalli** [comment]
> This pull request is for translation delivery. Please review and approve them.

These keys need to be added again:
```xml
validation_rules_result_valid_result_button
validation_rules_result_valid_result_title
validation_rules_result_valid_result_country_and_time
validation_rule_technical_error_date_format
validation_rule_technical_error_date_expired

start_validation_rule_check_button
start_validation_rule_check_loading_text

person_overview_no_certificates_subtitle_2

rat_qr_code_profile_information_item
rat_qr_code_profile_edit_item

```

**Comment by harambasicluka** [comment]
Maybe we should wait for the next translation delivery on Wednesday. This should fix all of this.

**Comment by service-tip-git** [comment]
This pull request is for translation delivery. Please review and approve them.

**Comment by mtwalli** [comment]
Those keys are repeated in default values , I think we should remove the DE ones. I don't have access to the repo , I could have pushed it
```
    <string name="validation_start_no_internet_dialog_title">
    <string name="validation_start_no_internet_dialog_msg">
    <string name="validation_start_no_internet_dialog_positive_button">
```

**Comment by harambasicluka** [comment]
I think if needed changes in the past we created our on branch from this one. But i think you should be able to change stuff on this pr as editing via the web ui is possible.

**Review by mtwalli — APPROVED** [review]

**Comment by mtwalli** [comment]
> I think if needed changes in the past we created our on branch from this one. But i think you should be able to change stuff on this pr as editing via the web ui is possible.

Worked

**Review by axelherbstreith — APPROVED** [review]

**Pull request merged**
