### PR TITLE
fixed fake key submission not setting the cwa-fake header correctly

### PR DESCRIPTION
**Pull request by LostMekka**
## Description
This PR accompanies issue #448, which discusses a potential oversight in the code, that could result in a bug later on. In short, Math.random().toInt().toString() will always be evaluated to "0", which defeats the point of the faked parameter.

In the checklist above, the check mark for the tests is missing, since there currently is no code path that executes the problematic statement.

### CODE REVIEW

**Comment by jakobmoellersap** [comment]
Hi, as far as I know, the CWA-Fake Header should be Random. That means that we cannot simply set Fake to 1 but should try to have an effort in actually changing the value to a random integer unequal to zero. I agree though that the current implementation does not work correctly either.

**Comment by LostMekka** [comment]
Maybe I don't yet fully understand the purpose of the fake requests, but I cannot imagine, why it would be beneficial to set a random value there. If the purpose is to prevent other users to detect when I am making a real request, then I just need to make fake requests at *random intervals*.
- If the connection would be unsecured, then any other person could read the header and trivially distinguish between fake and real requests. In that case, the header would be useless.
- If the connection is secured, (HTTPS) others can only see *that* a request is sent, but the value of the fake header is encrypted, so there is no benefit from having different values there.

**Comment by jakobmoellersap** [comment]
Thanks for your input. We are in the process of looking at this together with the backend team and will reach out here once we have a more clear decision on how the interface should behave.

**Comment by jakobmoellersap** [comment]
Not relevant as we now have a new Approach (see Playbook)

**Pull request closed without merging**
