### PR TITLE
Bring TracingExplanationDialog back (EXPOSUREAPP-5813)

### PR DESCRIPTION
**Pull request by jurajkusnier**
**Fixing**
Tracing explanation dialog got removed from the onboarding process
**Testing**
Reset app & go through onboarding. You should see the Tracing explanation dialog with new strings.

### CODE REVIEW

**Review by harambasicluka — COMMENTED** [review]
image
looks good :)

@ralfgehrer should we keep the string changes in to not trigger a new translation? But this will cause merge problems with the translation delivery tomorrow...

**Comment by harambasicluka** [comment]
I also tested an update to a newer version (`VERSION_MAJOR=2`) and it isn't shown again 👍

**Comment by jurajkusnier** [comment]
> @ralfgehrer should we keep the string changes in to not trigger a new translation? But this will cause merge problems with the translation delivery tomorrow...

Everything in the PR is already translated and some texts were removed in the previous commits so we need to update string files anyway to display something in the popup.

**Comment by ralfgehrer** [comment]
> @ralfgehrer should we keep the string changes in to not trigger a new translation? But this will cause merge problems with the translation delivery tomorrow...

Let's keep the changes here and request another translation upload once merged.

**Review by ralfgehrer — APPROVED** [review]
LGTM. Tested on Pixel (Andoid 10)

**Review by harambasicluka — APPROVED** [review]

**Pull request merged**
