### PR TITLE
Add card (EXPOSUREAPP-7445)

### PR DESCRIPTION
**Pull request by jurajkusnier**
image

### CODE REVIEW

**Review by ChristinaTsigganos — DISMISSED** [review]
UA approved

**Review by kolyaopahle — DISMISSED** [review]
LGTM 👍

**Review by kolyaopahle — APPROVED** [review]

**Review by axelherbstreith — APPROVED** [review]
👍

**Review by ChristinaTsigganos — APPROVED** [review]
UA approved

**Pull request merged**
