### PR TITLE
App Update (EXPOSUREAPP-8905)

### PR DESCRIPTION
**Pull request by mtwalli**
### Testing 
1- Please use gmail testing account 
2- Follow the steps sent by email message that has subject `Testing - In App Update Google play`
3- you should see something like 
Screenshot 2021-09-21 at 17 56 56

- [x] Pending on Google play console testing

### CODE REVIEW

**Review by AlexanderAlferov — APPROVED** [review]
Works 🚀 
I think guide should be updated: update dialog would pop-up only if you reopen application (swipe away and then reopen).

**Comment by SamuraiKek** [comment]
App is minimizing once the update is complete on my Samsung Galaxy S10+ (Android 11). Is this normal? It happens every time.

https://user-images.githubusercontent.com/19816790/134343308-eb465334-9172-49d4-8ea1-cada23254b7b.mp4

**Comment by mtwalli** [comment]
> App is minimizing once the update is complete on my Samsung Galaxy S10+ (Android 11). Is this normal? It happens every time.
> 
>  Screen_Recording_20210922-152451_Corona-Warn.mp4

I have no idea 🤷, there is no intents triggered explicitly, Google play App is opening the app again

**Review by SamuraiKek — APPROVED** [review]

**Comment by SamuraiKek** [comment]
> > App is minimizing once the update is complete on my Samsung Galaxy S10+ (Android 11). Is this normal? It happens every time.
> > Screen_Recording_20210922-152451_Corona-Warn.mp4
> 
> I have no idea 🤷, there is no intents triggered explicitly, Google play App is opening the app again
> BUT there is something weird in your video:
> it is was Downloading -> Installing -> Downloading again ?!!

Juts Google Play things I guess 🤷

**Pull request merged**
