### PR TITLE
Fixing the "Broken link in documentation" (closes #653)

### LINKED ISSUE #653: Broken link in documentation
Here: https://github.com/corona-warn-app/cwa-app-android/blob/master/docs/architecture-overview.md

Link to https://github.com/corona-warn-app/cwa-server/blob/master/docs/architecture-overview.md does not work, page not found.

### PR DESCRIPTION
**Pull request by pr1metine**
## Checklist

* [x] Test your changes as thoroughly as possible before you commit them. Preferably, automate your test by unit/integration tests.
* [x] If this PR comes from a fork, please [Allow edits from maintainers](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)
* [x] Set a speaking title. Format: {task_name} (closes #{issue_number}). For example: Use logger (closes # 41)
* [x] [Link your Pull Request to an issue](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) (if applicable)
* [x] Create Work In Progress [WIP] pull requests only if you need clarification or an explicit review before you can continue your work item.
* [x] Make sure that your PR is not introducing _unnecessary_ reformatting (e.g., introduced by on-save hooks in your IDE)
* [x] Make sure that your PR does not contain changes in strings.xml (see issue #332)
* [x] Make sure that your PR does not contain compiled sources (already set by the default .gitignore) and / or binary files

## Description

This PR ensures that all links inside the architecture overview documentation work properly. While I am at it I also made some tweaks regarding the language. Since these changes only affect one documentation page I figured that this PR can be pushed directly to the master branch.

### CODE REVIEW

**Comment by pr1metine** [comment]
```
INFO: ------------------------------------------------------------------------
INFO: EXECUTION FAILURE
INFO: ------------------------------------------------------------------------
INFO: Total time: 14.577s
INFO: Final Memory: 7M/96M
INFO: ------------------------------------------------------------------------
ERROR: Error during SonarQube Scanner execution
ERROR: Parameter 'sonar.pullrequest.branch' is mandatory for a pull request analysis
ERROR: 
ERROR: Re-run SonarQube Scanner using the -X switch to enable full debug logging.

Exited with code exit status 2
```

**Comment by pr1metine** [comment]
Ops, I think I broke CI.

**Comment by jakobmoellersap** [comment]
please try a commit to reinstatiate the CI

**Comment by pr1metine** [comment]
This PR is fubar. I'ma try with a new one.

**Pull request closed without merging**
