### PR TITLE
Translation Delivery

### PR DESCRIPTION
**Pull request by service-tip-git**
Translation Delivery

### CODE REVIEW

**Comment by service-tip-git** [comment]
This pull request is for translation delivery. Please review and approve them.

**Review by mtwalli — DISMISSED** [review]

**Comment by Ein-Tim** [comment]
Here are two dots at the end of the sentence: https://github.com/corona-warn-app/cwa-app-android/blob/a1110d3d0906273936ef1db7e8024ec581f8dfbc/Corona-Warn-App/src/main/res/values/strings.xml#L261
This should be fixed.

**Review by Ein-Tim — CHANGES_REQUESTED** [review]
Here are two dots at the end of the sentence: https://github.com/corona-warn-app/cwa-app-android/blob/a1110d3d0906273936ef1db7e8024ec581f8dfbc/Corona-Warn-App/src/main/res/values/strings.xml#L261
This should be fixed.

**Comment by mtwalli** [comment]
> Here are two dots at the end of the sentence:
> 
> https://github.com/corona-warn-app/cwa-app-android/blob/a1110d3d0906273936ef1db7e8024ec581f8dfbc/Corona-Warn-App/src/main/res/values/strings.xml#L261
> 
> 
> This should be fixed.

@Ein-Tim 
is it part of this PR? I don't see it here

**Comment by Ein-Tim** [comment]
@mtwalli No, but I suggest to change it either with this or the next PR (-:

**Comment by mtwalli** [comment]
> @mtwalli No, but I suggest to change it either with this or the next PR (-:

This is a translation of newly added/changed strings . Please file a separate issue ?

**Comment by Ein-Tim** [comment]
@Mtwalli

FYI: https://github.com/corona-warn-app/cwa-app-ios/pull/4066#pullrequestreview-848171943 

I'll go ahead and file a new issue, but as you can see in the PRs linked to from my comment, @marcuscc stated that this should be fixed with the next translation delivery.

**Comment by Ein-Tim** [comment]
@mtwalli Issue https://github.com/corona-warn-app/cwa-documentation/issues/803 created.

**Comment by mtwalli** [comment]
@Ein-Tim If you see the repo where this PR was initiated. you will notice that is not part of cwa-android. Translation delivery comes from the translation team, if we do the change you suggest here it will be overridden with the next delivery. So it is better to file an issue so translation team can take of it. I hope that is clear now

**Comment by service-tip-git** [comment]
This pull request is for translation delivery. Please review and approve them.

**Pull request merged**
