### PR TITLE
Fix - Exposure windows keep adding (EXPOSUREAPP-4020)

### PR DESCRIPTION
**Pull request by BMItr**
#This PR adresses:
(EXPOSUREAPP-4020)

- ExposureWindows were added before resulting in a longer list
- Adjustement in persistance were neccessary to have the correct exposure windows (for the relevant riskresult)
- Only affects testersbuild / testmenu

#Screenshot (correct count):

correctNumber

### CODE REVIEW

**Review by d4rken — DISMISSED** [review]

**Review by d4rken — COMMENTED** [review]
You need to fix the failing tests though.

**Comment by BMItter** [comment]
> You need to fix the failing tests though.

tests should run now..
Feel free to merge, if time pressures.
Currently adding some advanced tests to higher coverage.

**Review by d4rken — APPROVED** [review]

**Review by kolyaopahle — APPROVED** [review]

**Comment by BMItter** [comment]
very nice test! :ok_hand:

**Comment by BMItter** [comment]
> very nice test! 👌

thank you :wink:

**Pull request merged**
