### PR TITLE
PPA should only collect data for PCA tests (EXPOSUREAPP-6598)

### PR DESCRIPTION
**Pull request by LukasLechnerDev**
### Description
This PR makes sure that only PPA for PCA tests and not RAT tests are collected. PPA for RAT tests will be implemented in an upcoming sprint. In order for this to work, I had to pass the `testType` to a few additional fragments via `navArgs`.

### How to test: 
- Submit positive PCR test
- Check TestMenu => Data Donation => Create Current Analytics (card on the very bottom)
- values for `key_submission_metadata_set` and `test_result_metadata_set ` should be there

- reset app
- Submit positive RAT test 
- Check TestMenu => Data Donation => Create Current Analytics (card on the very bottom)
- **No** values for `key_submission_metadata_set` and `test_result_metadata_set ` should be there

### CODE REVIEW

**Comment by chiljamgossow** [comment]
The call to reportAdvancedConsentGiven() is missing. Please check https://github.com/corona-warn-app/cwa-app-android/pull/2907

**Comment by LukasLechnerDev** [comment]
> The call to reportAdvancedConsentGiven() is missing. Please check #2907

Thanks! Added it like you did in the PR.

**Review by d4rken — APPROVED** [review]
lgtm, nice tests.

Found a bug not caused by this PR, #2938 2938

**Review by chiljamgossow — APPROVED** [review]
Looking good

**Pull request merged**
