### PR TITLE
Adapt CollapsingToolbarLayout to end at half height (EXPOSUREAPP-12346)

### PR DESCRIPTION
**Pull request by schauersbergern**
Adapt CollapsingToolbarLayout to end at half height 
of the first element of the certificates list

### CODE REVIEW

**Review by SamuraiKek — COMMENTED** [review]
Great work! Will approve after rebasing to `2.22`

**Comment by schauersbergern** [comment]
> 

Rebased on 2.22.x and changed target branch

**Review by SamuraiKek — APPROVED** [review]

**Comment by KathrinLuecke** [comment]
Nothing changed in the strings - I don't think UA needs to approve this, right?

**Comment by mtwalli** [comment]
> Nothing changed in the strings - I don't think UA needs to approve this, right?

Not required

**Review by chiljamgossow — APPROVED** [review]
Tested, looking good!

**Pull request merged**
