### PR TITLE
Fix Presence tracing Crash (EXPOSUREAPP-7751)

### PR DESCRIPTION
**Pull request by mtwalli**
- Issue :  `QRCodeUriParser.getQrCodePayload` errors were not handled in `CheckInsViewModel.verifyUri`
- Fix: Apply same error handling as in `ScanCheckInQrCodeViewModel.onScanResult`

To verify run the unit tests without the `try catch` handling 

### Testing 
https://e.coronawarn.app?v=1#CAESCwgBEgJTZBoDRGRkGnYIARJgPHJPttiOJsB3H0nszaVA3YYPSSEaJpsgcJJgukcoXN9Q5em5FnGLbaC0XiCs3WQWLkMoP3NgEXtcgoVAGSoWAZf4k4--sE2KHkqb4EVYir1hI89vsQ8ayF2Pkdjh9BkDGhD0LoYTvbzjjzfzPoEzgFASIgYIARAHG

### CODE REVIEW

**Review by d4rken — APPROVED** [review]
lgtm

**Review by BMItr — APPROVED** [review]

**Comment by harambasicluka** [comment]
Please do not merge before we have find the cause for the white screen when clicking back.

**Comment by mtwalli** [comment]
I will create another PR for this issue

**Comment by mtwalli** [comment]
PR for blank screen: https://github.com/corona-warn-app/cwa-app-android/pull/3409

**Pull request merged**
