### PR TITLE
Introduce skeleton classes for UI tests and screenshots (EXPOSUREAPP-2997)

### PR DESCRIPTION
**Pull request by d4rken**
Submission refactoring and many skeletons for UI tests, and some fastlane screenshot logic.

Getting this merge ready such that it does not become too stale too merge.

Replaces #1467 

## Test
* Perform TAN submission
* Perform QR submission
* Check Calendar UI behavior

### CODE REVIEW

**Comment by BMItter** [comment]
Checked on WRU-XD, 

- QR-Code behaviour (invalid, pending, positve, negativ), all passed.
- TAN behaviour (3 TANS), all passed

**Review by AlexanderAlferov — APPROVED** [review]
App tested. Calendar working fine. Lgtm

**Review by AndroidMedaGalaxy — APPROVED** [review]
QR and TAN submission flow tests were successful.

LGTM  “ヽ(´▽｀)ノ”

**Review by Kolpa — APPROVED** [review]
LGTM, still some more refactoring needed but too much to put into this pr as well

**Review by kolyaopahle — APPROVED** [review]
Now also approved using the right github account '^^

**Review by BMItr — APPROVED** [review]

**Pull request merged**
