### PR TITLE
Update EN SDK to 1.7.2 (EXPOSUREAPP-3662)

### PR DESCRIPTION
**Pull request by ralfgehrer**
Google Release notes for version  1.7: https://developers.google.com/android/exposure-notifications/release-notes

Shouldn't have any regression.

Nevertheless, please test:
- risk score calculation
- submitting a positive test result including the sharing of keys

### CODE REVIEW

**Comment by BMItter** [comment]
short note: Worker Upgrade will probably be integrated in this PR (offical reommendation by google with ENF 1.7.2), discussed with Ralf, (Max)

**Review by BMItr — APPROVED** [review]

**Review by harambasicluka — CHANGES_REQUESTED** [review]
Can't submit keys, need to verify if it's a problem on the updated dependencies. Tested on WRU.

```
2020-11-10 16:23:30.558 26215-26283/de.rki.coronawarnapp.test E/TaskController: Task failed: InternalTaskState(id=acf67c7e-8c1d-418e-8bbc-6c124da06c9f, request=DefaultTaskRequest(type=class de.rki.coronawarnapp.submission.SubmissionTask (Kotlin reflection is not available), arguments=de.rki.coronawarnapp.submission.SubmissionTask$Arguments@a4c7541, id=1c3b96f4-13ef-466d-a937-0121e57288a1), createdAt=2020-11-10T15:23:29.984Z, startedAt=2020-11-10T15:23:29.998Z, finishedAt=null, error=null, result=null, config=Config(executionTimeout=PT480S, collisionBehavior=ENQUEUE), job="coroutine#789":LazyDeferredCoroutine{Cancelled}@f8deae6, task=de.rki.coronawarnapp.submission.SubmissionTask@e34827)
    de.rki.coronawarnapp.exception.http.BadRequestException: error during web request, http status 400
        at de.rki.coronawarnapp.http.HttpErrorParser.intercept(HttpErrorParser.kt:41)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at de.rki.coronawarnapp.http.interceptor.RetryInterceptor.intercept(RetryInterceptor.kt:15)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:221)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at de.rki.coronawarnapp.http.interceptor.WebSecurityVerificationInterceptor.intercept(WebSecurityVerificationInterceptor.kt:11)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by harambasicluka** [comment]
> Can't submit keys, need to verify if it's a problem on the updated dependencies. Tested on WRU.
> 
> ```
> 2020-11-10 16:23:30.558 26215-26283/de.rki.coronawarnapp.test E/TaskController: Task failed: InternalTaskState(id=acf67c7e-8c1d-418e-8bbc-6c124da06c9f, request=DefaultTaskRequest(type=class de.rki.coronawarnapp.submission.SubmissionTask (Kotlin reflection is not available), arguments=de.rki.coronawarnapp.submission.SubmissionTask$Arguments@a4c7541, id=1c3b96f4-13ef-466d-a937-0121e57288a1), createdAt=2020-11-10T15:23:29.984Z, startedAt=2020-11-10T15:23:29.998Z, finishedAt=null, error=null, result=null, config=Config(executionTimeout=PT480S, collisionBehavior=ENQUEUE), job="coroutine#789":LazyDeferredCoroutine{Cancelled}@f8deae6, task=de.rki.coronawarnapp.submission.SubmissionTask@e34827)
>     de.rki.coronawarnapp.exception.http.BadRequestException: error during web request, http status 400
>         at de.rki.coronawarnapp.http.HttpErrorParser.intercept(HttpErrorParser.kt:41)
>         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
>         at de.rki.coronawarnapp.http.interceptor.RetryInterceptor.intercept(RetryInterceptor.kt:15)
>         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
>         at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:221)
>         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
>         at de.rki.coronawarnapp.http.interceptor.WebSecurityVerificationInterceptor.intercept(WebSecurityVerificationInterceptor.kt:11)
>         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
>         at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
>         at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
>         at java.lang.Thread.run(Thread.java:764)
> ```

It worked with a teletan on WRU-XD.

**Review by harambasicluka — APPROVED** [review]
Can't reproduce, tested it multiple times... 🌟

**Pull request merged**
