### PR TITLE
Country prefix +49 for hotline is misleading(EXPOSUREAPP-4677)

### PR DESCRIPTION
**Pull request by mtwalli**
1- Remove `+49` from hotline numbers 
2- Adjust Instruction text about it. (DE, EN, Default) Strings

device-2021-01-21-130853
device-2021-01-21-130937

### CODE REVIEW

**Comment by AlexanderAlferov** [comment]
Please, kindly check submission_contact_step_1_content in strings that is used in include_submission_contact.xml in content description.

**Review by axelherbstreith — DISMISSED** [review]

**Comment by mtwalli** [comment]
> Please, kindly check submission_contact_step_1_content in strings that is used in include_submission_contact.xml in content description.

Thx, I have adjusted it, Please let me know if it is Ok

**Review by AlexanderAlferov — APPROVED** [review]
Great!

**Review by BMItr — APPROVED** [review]

**Review by janetback — APPROVED** [review]
UA reviewed

**Comment by MikeMcC399** [comment]
Link back to https://github.com/corona-warn-app/cwa-documentation/issues/501.

**Pull request merged**
