### PR TITLE
Updated NotificationHelper to use highest notification priority (PRIORITY_MAX)

### LINKED ISSUE #202: Setting Notification Priority to PRIORITY_MAX
## Current Implementation

Currently, the notification priority for notifications from the corona-warn app is set to PRIORITY_HIGH.

## Suggested Enhancement

We should set the notification priority to PRIORITY_MAX. See pull request here: #203

## Expected Benefits

Setting the notification priority to the highest possible value will ensure that on all android devices notifications from the corona-warn app have the highest priority and will be recognized.

### PR DESCRIPTION
**Pull request by jomapp**
We should ensure that notifications always have the highest priority also on older devices.
Resolves #202

## Checklist

* [x] Test your changes as thoroughly as possible before you commit them. Preferably, automate your test by unit/integration tests.
* [x] If this PR comes from a fork, please [Allow edits from maintainers](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)
* [x] Set a speaking title. Format: {task_name} (closes #{issue_number}). For example: Use logger (closes # 41)
* [x] [Link your Pull Request to an issue](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) (if applicable)
* [x] Create Work In Progress [WIP] pull requests only if you need clarification or an explicit review before you can continue your work item.
* [x] Make sure that your PR is not introducing _unnecessary_ reformatting (e.g., introduced by on-save hooks in your IDE)

### CODE REVIEW

**Comment by timbrueggenthies** [comment]
To use the high priority, it is also needed to adjust this setting on the NotificationChannel on Devices >= API 26 (see [here](https://developer.android.com/reference/android/app/Notification.Builder#setPriority(int)))

**Comment by jomapp** [comment]
> To use the high priority, it is also needed to adjust this setting on the NotificationChannel on Devices >= API 26 (see [here](https://developer.android.com/reference/android/app/Notification.Builder#setPriority(int)))

For the NotificationChannel the current setting ("IMPORTANCE_HIGH") is already the highest. The Google documentation specifies "unused" for "IMPORTANCE_MAX". (see [here](https://developer.android.com/reference/android/app/NotificationManager#IMPORTANCE_MAX))

**Comment by timbrueggenthies** [comment]
Okey, didn't knew that. Thanks for pointing out! 👍

**Comment by jomapp** [comment]
> Okey, didn't knew that. Thanks for pointing out! 👍 

Sure :) Was also quite surprised seeing that "IMPORTANCE_MAX" is not used anymore.

**Comment by HeeTattSap** [comment]
@jomapp thank you for your contribution this. As you already correctly noted, we are using PRIORITY_HIGH because PRIORITY_MAX is not in used.

**Comment by jomapp** [comment]
> @jomapp thank you for your contribution this. As you already correctly noted, we are using PRIORITY_HIGH because PRIORITY_MAX is not in used.

No, it's different from what you wrote. In the project we are currently using IMPORTANCE_HIGH, for the NotificationChannel, which is fine (since IMPORTANCE_MAX is unused.) But for the notification itself we should use PRIORITY_MAX instead of PRIORITY_HIGH since for older devices below API 26 this ensures that notifications are also shown with the highest priority. 
Infact: IMPORTANCE_HIGH (>= API 26) == PRIORITY_MAX (< API 26)

**Comment by jomapp** [comment]
Can we reopen this PR? I think it's relevant (please see my last comment) Thank you!

**Comment by HeeTattSap** [comment]
@jomapp thank you. I misunderstood that this was about the channel. 

Your fix works and I have validated this on  Android 6 and Android 10 devices. We will merge this change :)

**Comment by jomapp** [comment]
@HeeTattSap thanks! No worries, thank you for merging it :)

**Pull request merged**
