### PR TITLE
Add app shortcuts to primary targets (EXPOSUREAPP-5414)

### PR DESCRIPTION
**Pull request by mtwalli**
## Ticket
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5414

## Current State
- Shortcuts are displayed correctly and get disabled when onboarding is not yet complete or the user is in the middle of the submission flow
- Scanner shortcut is disabled when camera permission is not granted

## Open Tasks
- [x] Check-In Shortcut always navigates to Checkin-Onboarding Screen in which no blue "OK" button is displayed.
- [x] Certificate-Onboarding is not shown on first usage
- [x] Shortcut navigation sometimes doesn't work when the app is in background (I suspect this is because we are calling `processExtraParameters()` only `if(savedInstanceState == null)`

### CODE REVIEW

**Comment by dodekaphilist** [comment]
Why is this PR not getting published?

**Comment by mtwalli** [comment]
> Why is this PR not getting published?
Hi @dodekaphilist , the PR could not be merged for the following reasons: 
1- Feature party with iOS, the same feature should be implemented there too
2- The PR does not fulfill all acceptance criteria in the ticket 
3- Feature got less priority at  the moment, and the team is focusing now `CCL` (Covid Common Logic)  

Thanks for understanding, we will try to get it merged ASAP

**Comment by ln-12** [comment]
@mtwalli Well, on iOS we already have quick actions for diary and event check in. So feature parity is not given at the moment either.

**Comment by mtwalli** [comment]
> @mtwalli Well, on iOS we already have quick actions for diary and event check in. So feature parity is not given at the moment either.

@ln-12  Thanks for doing it for iOS too, but feature parity is one reasons. More important is to get it implemented as required 
see my comment https://github.com/corona-warn-app/cwa-app-android/pull/4642#issuecomment-1009982512

there is still some work to be done

**Comment by ln-12** [comment]
@mtwalli Please have a look at [this PR](https://github.com/corona-warn-app/cwa-app-android/pull/4854) in which I tried to solve the remaining shortcomings. Thanks!

**Comment by davidlindercwa** [comment]
@ln-12 Thanks a lot for all your help in this (and the new PR), much appreciated! We're examining the open PRs for both iOS & Android to--as discussed--make sure that we both have feature parity and also meet the requirements of the original story (which is also currently being reviewed & possibly updated slightly, as it was originally created quite some time ago). As @mtwalli wrote there's still some work here left to be done, but we're on it.

**Comment by mtwalli** [comment]
@ln-12 and  @dodekaphilist, I want to share some good news with you. @LukasLechnerDev  will continue on this PR to do final checks and complete it. 

Many thanks for your patience and contributions!

**Comment by ln-12** [comment]
Why isn't this feature already released? It was ready before 2.19 and now moved to 2.22?

**Comment by mtwalli** [comment]
> Why isn't this feature already released? It was ready before 2.19 and now moved to 2.22?

@ln-12 Please see the "Open Tasks" in the PR description? plus we have targeted Android 12 and that led to some navigation issues that we need to tackle first

**Review by KathrinLuecke — APPROVED** [review]
UA approved

**Review by BMItr — APPROVED** [review]
budspencer

lgtm! 👌

**Review by SamuraiKek — APPROVED** [review]
Very nice! Finally in after this much time :D

**Pull request merged**
