### PR TITLE
Run pulling results always(Dev)

### PR DESCRIPTION
**Pull request by mtwalli**
Run pulling results always regardless of the result of previous steps.
- Suppressing the error only did allow to grab the report ,but it gave false impression that the job succeeded.
- Verified in this build: https://app.circleci.com/pipelines/github/corona-warn-app/cwa-app-android/9145/workflows/736a7a5f-7c26-4978-af97-98f16443d6f5/jobs/50356

### CODE REVIEW

**Review by BMItr — DISMISSED** [review]

**Comment by d4rken** [comment]
Wait with merge until @LukasLechnerDev has confirmed this solves the missing test lab information.

**Comment by harambasicluka** [comment]
> Wait with merge until @LukasLechnerDev has confirmed this solves the missing test lab information.

This should than go against 1.12 as the fix is also for 1.12 -> https://github.com/corona-warn-app/cwa-app-android/pull/2257

**Comment by mtwalli** [comment]
> > Wait with merge until @LukasLechnerDev has confirmed this solves the missing test lab information.
> 
> This should than go against 1.12 as the fix is also for 1.12 -> #2257

Yes, I checked with @LukasLechnerDev. I updated the PR to address my findings there. A build on a copy of his branch linked above.

**Comment by d4rken** [comment]
Hm now 1.13.x is merged into this branch? Wasn't the idea to rebase it against 1.12.x?

**Comment by mtwalli** [comment]
New PR :https://github.com/corona-warn-app/cwa-app-android/pull/2262
Rebasing created endless conflicts

**Pull request closed without merging**
