### PR TITLE
Add app shortcuts to primary targets (closes #2858)

### LINKED ISSUE #2858: Add app shortcut to QR code scanner
### Current Implementation

There is a shortcut to the contact journal as suggested in corona-warn-app/cwa-wishlist#295.

### Suggested Enhancement

There should also be a shortcut to the QR code scanner for the new check-in functionality.

### Expected Benefits

Users could open the scanner with lightning speed :zap:

### Additional context

A CCTG user asked for this here: https://chaos.social/@Kurt/106082036510232318

---
Internal Tracking ID: [EXPOSUREAPP-5414](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5414) Android
Internal Tracking ID: [EXPOSUREAPP-5593](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5593) iOS
PR iOS corona-warn-app/cwa-app-ios#2235
PR iOS https://github.com/corona-warn-app/cwa-app-ios/pull/4238

### PR DESCRIPTION
**Pull request by dodekaphilist**
Fixes corona-warn-app#2858, also adds the other targets from the bottom bar menu

Please validate changes for potential problems

### CODE REVIEW

**Comment by mtwalli** [comment]
Please rebase to `release/2.16.x`

**Comment by dodekaphilist** [comment]
Anything more I need to do? I don't have much experience with GitHub

**Comment by mtwalli** [comment]
> Anything more I need to do? I don't have much experience with GitHub

@dodekaphilist 

First of all thank you very much for opening the PR!.  I'm afraid that your PR will take more time to be approved, since it is not entirely a decision that can be made by the dev team regarding this feature.
Thanks for your understanding!

**Comment by dodekaphilist** [comment]
As long as I did everything necessary, that's okay with me :)

**Comment by mtwalli** [comment]
@dodekaphilist , I have got a feedback regarding your PR:
1- Please fix `klint` issue 
2- The order of the shortcuts should be the as follows: 
         
          1. Scanner
          2. Zertifikate
          3. Check-ins
          4. Eintrag hinufügen 

3- Labels in German as follows:
      
          1. QR-Codes scannen
          2. Zertifikate anzeigen
          3. Check-ins anzeigen
          4. Eintrag hinzufügen


4- Please use the following [icons.zip](https://github.com/corona-warn-app/cwa-app-android/files/7846950/icon.zip)


5- The same rules apply for displaying shorts like for adding a contact journal entry such as:
    - Short are available when is Onboarded - display Information/legal screen for the relevant shortcut destination if user did not confirm it yet
    - In addition, if access to the camera was declined, the menu entry is hidden as well

if it is too much for you, or you don't have the time to address all of these requirements, please let us know we can take care of it from here ;)

**Comment by dodekaphilist** [comment]
I fixed the easy things. As the control wether the shortcuts should be shown or not currently isn't implemented in any form, I would like to hand over the additional work to you :)

**Review by KathrinLuecke — COMMENTED** [review]
UA approved

**Pull request merged**
