### PR TITLE
Fix duration text overflow in check ins screen. (EXPOSUREAPP-7199)

### PR DESCRIPTION
**Pull request by SamuraiKek**
Text used to stretch out on a second row when font size was set to max in Android settings.

### CODE REVIEW

**Comment by dsarkar** [comment]
Fixes https://github.com/corona-warn-app/cwa-app-android/issues/3086

**Comment by MikeMcC399** [comment]
I successfully verified the fix using the steps from #3086.

**Review by d4rken — APPROVED** [review]
lgtm

**Review by mtwalli — APPROVED** [review]
Tested on Samsung S9

**Pull request merged**
