### PR TITLE
Use ContextCompat when accessing color resources (EXPOSUREAPP-4419) (#1924)

### PR DESCRIPTION
**Pull request by fynngodau**
As discussed in #1924, this PR replaces calls to `Context.getColor` with calls to the compat class `ContextCompat.getColor`.

It does not introduce any functional difference to the application, but reduces maintenance workload for our fork of the app, which has Android 5 support.

The tests were changed accordingly: depending on how the tests worked, some now `verify` that `ContextCompat.getColor` is being called instead of `Context.getColor`, some mock both `Context.getColor` as well as `Context.getResources().getColor` (one of which the compat class always calls).

Internal Tracking ID: [EXPOSUREAPP-4419](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4419)

### CODE REVIEW

**Comment by fynngodau** [comment]
I almost forgot to mention it: I would like to warmly wish everyone involved with CWA a happy new year!

**Comment by dsarkar** [comment]
@fynngodau, Thanks, and a  Happy New Year! Devs are made aware of this PR. DS

---
Corona-Warn-App Open Source Team

**Comment by mtwalli** [comment]
Thanks for the PR!. IMHO it would have been easier if we can just create an extension function for `Context` 
 like : `fun Context.getColorCompat(@ColorRes colorRes: Int) = ContextCompat.getColor(this, colorRes)`

and for callers, the only change would be appending  `Compat` such as  `context.getColorCompat(R.color.someColorRes)` and for testing, just provide the following stub ` every { context.getColorCompat(any()) } returns 1` and no need to provide stubs for `getColor` in Context and Resources. what do you think about that?

For more information on how to mock extension functions please have a look here: https://mockk.io/#extension-functions

**Review by mtwalli — DISMISSED** [review]
Thanks! LGTM

**Comment by fynngodau** [comment]
From your pipeline it looks like the tests are failing, aren't they? I was still about to keep trying to run them locally to find out what is up (I'm experiencing some issues with my setup).

Once that would have been resolved, I was going to say that I wasn't really aware of the extension functions feature of Kotlin. It does indeed look like a cleaner solution to me.

**Comment by d4rken** [comment]
> Task :Corona-Warn-App:ktlintMainSourceSetCheck
/home/circleci/project/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/ContextExtensions.kt:19:1: Unexpected blank line(s) before "}"

You can ignore `klint` and `detekt` until completely done, it's just LINTing stuff.

>  (the output of which I don’t have access to) 

It might ask you for a github login, but I think any github account should work as the project is open source. Have you tried to just log in with @fynngodau ?

@PhilippNowak96 Didn't you have the same issue initially, did you manage to access CI logs?

**Review by d4rken — DISMISSED** [review]
lgtm :coffee:

**Comment by PhilippNowak96** [comment]
@d4rken @fynngodau yes, I did. You need to click the "Details" link, login with your GitHub Account and then click the details link once again (because you only see your own CWA fork for the first time). After clicking the details link again you should see the respective data and also a little popup in the bottom right corner to follow the original CWA project. That should do the trick.

**Comment by fynngodau** [comment]
You're right that I *do* have access once I authenticate. The reason I didn't try that was because I understood that @PhilippNowak96 was not able to access it too, and therefore I didn't want to agree to their ToS.

What I had been missing yesterday were mostly some imports, I added them this morning.

From my side the PR would be done, I'll just push another commit that fixes the lint (I was now also able to run it locally).

**Review by d4rken — APPROVED** [review]

**Review by ralfgehrer — APPROVED** [review]

**Comment by fynngodau** [comment]
Thank you, everyone! :tada:

**Pull request merged**
