### PR TITLE
Change texts to stipulate TAN hotline for PCR tests only (EXPOSUREAPP-6585)

### PR DESCRIPTION
**Pull request by janetback**
### Description
Changed TAN-related UI texts to specify that they refer to PCR tests only (as opposed to Rapid Tests) - see also EXPOSUREAPP-6585.

### CODE REVIEW

**Review by harambasicluka — APPROVED** [review]

**Comment by Ein-Tim** [comment]
@harambasicluka Why has this been merged into the `release/2.0.x` branch?

**Comment by d4rken** [comment]
@Ein-Tim Early morning mistake, thanks for the heads up :heart:

**Comment by janetback** [comment]
@Ein-Tim thanks for pointing this out. This was my mistake.

**Comment by Ein-Tim** [comment]
@janetback @d4rken 

No problem, always happy to help. This isn't live in the Android app now, or?

**Pull request merged**
