### PR TITLE
Global 7 day infections and hospitalisation incidents (EXPOSUREAPP-9833)

### PR DESCRIPTION
**Pull request by AlexanderAlferov**
## Features
New combined card for 7 day infection and hospitalisation incidents.

Screenshot 2021-10-11 at 15 45 02

## Jira
[Ticket](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9833)
[Story](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9449)

## How to test:
1) Run the application
2) Check the card
3) Enable accessibility features "Text to speech" and listen the card

### CODE REVIEW

**Review by KathrinLuecke — DISMISSED** [review]
UA approved

**Review by SamuraiKek — DISMISSED** [review]
Very nice, looks good 🚀

**Review by jurajkusnier — COMMENTED** [review]
Looks good! Just one minor thing, card padding on the bottom should be bigger. It's visible when you enlarge the font size.

image

**Review by jurajkusnier — APPROVED** [review]

**Review by SamuraiKek — APPROVED** [review]

**Review by KathrinLuecke — APPROVED** [review]
UA approved

**Pull request merged**
