### PR TITLE
UA typo fix (DEV)

### PR DESCRIPTION
**Pull request by ChristinaTsigganos**
changed "abrufen" to "abzurufen"

### CODE REVIEW

**Comment by DerVogel2020** [comment]
In my opinion,  it should also be "und andere zu warnen".
Or both like before: You **can** fetch your test result and **can** warn others.

**Review by mtwalli — APPROVED** [review]

**Review by d4rken — APPROVED** [review]

**Comment by d4rken** [comment]
> In my opinion, it should also be "und andere zu warnen".
> Or both like before: You can fetch your test result and can warn others.

What do you think @ChristinaTsigganos ?

**Review by NataliaLemmerth — APPROVED** [review]
UA approved

**Comment by ChristinaTsigganos** [comment]
> > In my opinion, it should also be "und andere zu warnen".
> > Or both like before: You can fetch your test result and can warn others.
> 
> What do you think @ChristinaTsigganos ?

Thank you very much for your contribution, @DerVogel2020! We've adapted the text to make it easier to read.

**Review by SamuraiKek — APPROVED** [review]

**Pull request merged**
