### PR TITLE
FIX: Export test results shown in contact journal (EXPOSUREAPP-11441)

### PR DESCRIPTION
**Pull request by jurajkusnier**
### Testing
- Scan some positive/negative PCR/RAT tests 
- Check tests in the contact journal
- Export Entries
- Tests should be visible in the exported data

### Jira Ticket
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11441

### Contact Journal (Export of Data) Spec
https://github.com/corona-warn-app/cwa-app-tech-spec/blob/main/docs/spec/contact-diary.md#export-of-data

### CODE REVIEW

**Review by chiljamgossow — COMMENTED** [review]
I tested, and it works fine if there are also other entries.
But with RAT tests only, there was no entry in the export. Is that intended?

**Comment by jurajkusnier** [comment]
> I tested, and it works fine if there are also other entries.
> But with RAT tests only, there was no entry in the export. Is that intended?

Fixed and new test case was added

**Review by BMItr — APPROVED** [review]
lgtm.
tested on Samsung S20 Device.
image

**Review by mtwalli — APPROVED** [review]

**Comment by DerVogel2020** [comment]
My browser cannot find the specs at

https://github.com/corona-warn-app/cwa-app-tech-spec/blob/main/docs/spec/contact-diary.md#export-of-data

Where can I find them?

**Pull request merged**
