### PR TITLE
Rewrite base45 encoding/decoding, delete vaccination certificates with malformed base45 (Community) EXPOSUREAPP-10556

### PR DESCRIPTION
**Pull request by floscher**
### Description
A while ago I wrote a Kotlin multiplatform (Java/JS) base45 encoder, I adapted it a bit for this project and this PR proposes to use that for base45 encoding/decoding, in case you would like to use that. It was built with the goal to produce the same results as the encoder you currently use, but developed from scratch independently.

It's more compact and in my opinion more readable and as far as I can see it also takes edge cases into account that were fixed e.g. in #4341 for the currently used encoder.

---
Internal Tracking ID: [EXPOSUREAPP-10556](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10556)

### CODE REVIEW

**Comment by floscher** [comment]
The PR is now updated to no longer have merge conflicts.

Also it now also addresses #4368 in a slightly different way. The decoder now does not throw exceptions, but returns an object of type `DecodingFailure` when decoding fails. This should help prevent crashes caused by uncatched exceptions.

This also made more changes necessary, especially to `VaccinationContainer`, where the contents of the certificate are nullable (in case of decoding failure).

For now vaccination certificates with malformed Base45 that were imported in a previous version are silently deleted and no longer displayed. I'd prefer if they were just marked as invalid, but for now it was easier to just simply drop them.

**Comment by dsarkar** [comment]
@floscher Thanks. Internal Tracking ID: [EXPOSUREAPP-10556](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10556)

**Comment by floscher** [comment]
Note: I noticed that these edge cases are currently not addressed in this PR:
https://github.com/ehn-dcc-development/hcert-kotlin/blob/af2aa4da2288548258ee2fe8c0a987c288438ec8/src/commonMain/kotlin/ehn/techiop/hcert/kotlin/chain/common/Base45Encoder.kt#L55-L56

Will add a commit fixing them later, when I have time again.

**Comment by floscher** [comment]
Ok, now the decoder should recognize these edge cases too, where three characters in base45 are too big to fit into two bytes, or when two characters in base45 are too big to fit into one byte.

And I also added the suggestion from https://github.com/corona-warn-app/cwa-app-android/pull/4341#issuecomment-965129908

**Comment by davidlindercwa** [comment]
Thanks a lot for submitting this, and apologies for the delayed response! We'll be looking at it as soon as we can.

**Comment by chiljamgossow** [comment]
@floscher Thank you very much for your contribution. We appreciate the time effort you have put into this. 
We are required to follow the reference implementation provided by the EU and therefore cannot include you PR.
So I kindly ask you to close the PR.

**Comment by vaubaehn** [comment]
Skip to content
corona-warn-app
/
cwa-app-android
Public
Code
Issues
115
Pull requests
6
Actions
Projects
1
Wiki
Security
Insights
Jump to bottom
Mitigate base45 security vulnerability (EXPOSUREAPP-10454) #4341
 Merged
jurajkusnier merged 4 commits into release/2.13.x from fix/10454-base45 16 days ago
 Merged
Mitigate base45 security vulnerability (EXPOSUREAPP-10454)
#4341
jurajkusnier merged 4 commits into release/2.13.x from fix/10454-base45 16 days ago
Conversation 7
Commits 4
Checks 1
Files changed 4
Conversation
 
@chiljamgossow chiljamgossow commented 17 days ago • 
covered by unit tests

@chiljamgossow
mitigate base45 security vulnerability
84fb384
@chiljamgossow chiljamgossow added the maintainers label 17 days ago
@chiljamgossow chiljamgossow added this to the 2.13.0 milestone 17 days ago
@chiljamgossow chiljamgossow requested a review from as a code owner 17 days ago
@chiljamgossow chiljamgossow changed the title mitigate base45 security vulnerability Mitigate base45 security vulnerability (EXPOSUREAPP-10454) 17 days ago
@chiljamgossow
detekt
36cce8b
@vaubaehn vaubaehn commented 17 days ago • 
😁
Is this actually a technical security risk, or more a good way to detect a broader range of fake DCCs?
(P.S.: I'm happy that SonarCloud/CircleCI don't complain about the unit test 😉 )

@chiljamgossow chiljamgossow commented 17 days ago
😁 Is this actually a technical security risk, or more a good way to detect a broader range of fake DCCs? (P.S.: I'm happy that SonarCloud/CircleCI don't complain about the unit test 😉 )

This has been reported as a security risk and the EU recommends to fix this. Fake DCC will be covered by other means.

mtwalli
mtwalli approved these changes 17 days ago
@mtwalli mtwalli self-assigned this 17 days ago
@mtwalli
Merge branch 'release/2.13.x' into fix/10454-base45
0618340
@vaubaehn vaubaehn commented 17 days ago • 
@chiljamgossow

This has been reported as a security risk and the EU recommends to fix this. Fake DCC will be covered by other means.

thanks for the clarification. The DCC that you use in your unit test was shared in a public discussion that possibly triggered the EU recommendation. From what I understood explained in other places where I looked into after your comment (ministero-salute/it-dgc-verificaC19-android#185 (comment) and following), some base45 decoders parse the valid beginning correctly, stop when reaching invalid parts but return back the valid (COSE) object that has already been decoded. The appended not decoded part may then include rubbish, in the case of the DCC that is also used in your unit test, some unpolite profanities... Even this may not be a security risk per se, it's probably a very good idea to adapt the decoder to be more strict...
Because that of protecting against such base45 tricking I thought, rejecting such QR codes will fight fake DCCs in parallel.
Enjoy your night!

@mtwalli mtwalli added the prio label 16 days ago
@mtwalli
Merge branch 'release/2.13.x' into fix/10454-base45
855cebf
@sonarcloud sonarcloud bot commented 16 days ago
Kudos, SonarCloud Quality Gate passed!    Quality Gate passed

Bug A 0 Bugs
Vulnerability A 0 Vulnerabilities
Security Hotspot A 0 Security Hotspots
Code Smell A 0 Code Smells

97.4% 97.4% Coverage
0.0% 0.0% Duplication

@jurajkusnier jurajkusnier self-assigned this 16 days ago
jurajkusnier
jurajkusnier approved these changes 16 days ago
@jurajkusnier jurajkusnier merged commit 51a7790 into release/2.13.x 16 days ago
11 checks passed
@jurajkusnier jurajkusnier deleted the fix/10454-base45 branch 16 days ago
@floscher floscher commented 16 days ago
@chiljamgossow @vaubaehn These changes from the original implementation might also be of interest, they seem to also cover some edge cases in Base45 encoding/decoding: ehn-dcc-development/hcert-kotlin@af2aa4d

@floscher floscher commented 15 days ago
These changes from the original implementation might also be of interest, they seem to also cover some edge cases in Base45 encoding/decoding: ehn-dcc-development/hcert-kotlin@af2aa4d

nvm, your PR seems to have fixed the same issues addressed in that commit, so you can ignore my comment(s)

@floscher floscher mentioned this pull request 15 days ago
Rewrite base45 encoding/decoding, delete vaccination certificates with malformed base45 (Community) EXPOSUREAPP-10556 #4356
 Closed
@vaubaehn vaubaehn commented 15 days ago
@chiljamgossow and @mtwalli
To be honest, I do not feel good to have that specific DCC for the unit test in our CWA code that you're using currently. Call me suspicious, but for me it has a bad karma...

I'd propose to use this instead:
HC1:NCFOXN%TSMAHN-H/RCMPQ5GE5I00H9GBH3QNAD6.LQLX85ZS GJTSJ4NKP1HCV4*XUA2PSGH.+H$NI4L6F$S-N1FYBRR1$Q1+GOF+P$HQPHQHTQ.SQ6$PUKRN95404.W7UX4795L*KDYPWGO+9AZDOHCRL35IWMSDOP7OQ+M70AK$8 96XY4SBLU96:/6N9R%EPL8RY9DOA60-K.IA.C8KRDL4O54O4IGUJKJGI0JAXD15IAXMFU*GSHGRKMXGG6DBYCBMQN:HG5PAHGG8KES/F-1JW-K%B3A9ENO4B-S-*O4-G1FD/U47HAE1MI4OE0G1:HHD4AB874MM-6B:HKJSQ.TAG3CR1638W9AV88G64PB4VHRY2EK03NFJL4M10KP3AT2VK LT5GGFV85I0*10W2ZXJSBTMFW*+KM2T8-CXR32BMF7RAEAYKMWHE/NH UP4SNGENEWUY97 -3YM0.HAM:D:00ZY35XRT1100MFKWEWYHKCZIZJ0CAQYIKOZIZJ0DAQCDQGAE62ORR7HL0POYQCGMGBBEQFCBCDCT4VYFQZEPYFXK69ZRV9T8IY6NWAYEJF0VXVKNFCG/X9UIG5HFWRPEDW2EPW00S1K83I3900:919GETVACCINATEDSOONDEARS9IKM24N21AW7ZUR2L013300WEWILLFIGHTCOVIDTOGETHERRS666I3AK96XYR01300PROTECTYOURSELFANDOTHERSANDBESAFELI5340XRT09SHUZVB33IR0FIGHTVIRUSHERE83H73KFI280I23KL0YRZT91Y0WITHLOVEFROMCWA*PWEOXCI/QXRLOZKN0LM*03I2RWT0Z

It has the same DCC contents, and it can be imported into CWA 2.6.1 without problem (CovPass and CovPassCheck refuse that DCC). So it provides same functionality for testing, but the hidden message is by far more appropriate.

If you agree, I may open a PR - or you may replace it yourself.

Thanks for your consideration!

@floscher floscher mentioned this pull request 14 days ago
Lenient mode for decoder (EXPOSUREAPP-10507) #4368
 Merged
floscher added a commit to floscher/cwa-app-android that referenced this issue 12 days ago
@floscher
Replace expletives in the invalidBase45 vaccination certificate …
6d797db
floscher added a commit to floscher/cwa-app-android that referenced this issue 12 days ago
@floscher
Replace expletives in the invalidBase45 vaccination certificate …
1362397
@vaubaehn vaubaehn commented 18 seconds ago
That's sad, indeed.
@chiljamgossow & @mtwalli But could you consider to replace the certificate for the unit test like suggested in #4341 (comment) , or is the cert/unit test also part of the EU reference implementation?



Leave a comment
Remember, contributions to this repository should follow its contributing guidelines and code of conduct.
 ProTip! Add .patch or .diff to the end of URLs for Git’s plaintext views.
Reviewers
@jurajkusnier
jurajkusnier
@mtwalli
mtwalli
Assignees
@jurajkusnier
jurajkusnier
@mtwalli
mtwalli
Labels
maintainers
prio
Projects
None yet
Milestone
2.13.0
Linked issues
Successfully merging this pull request may close these issues.

None yet

Notifications
Customize
You’re receiving notifications because you were mentioned.
5 participants
@chiljamgossow
@vaubaehn
@floscher
@jurajkusnier
@mtwalli
© 2021 GitHub, Inc.
Terms
Privacy
Security
Status
Docs
Contact GitHub
Pricing
API
Training
Blog
About
vaubaehn commented now That's sad, indeed. @chiljamgossow & @mtwalli But could you consider to replace the certificate for the unit test like suggested in #4341 (comment) , or is the cert/unit test also part of the EU reference implementation?

**Pull request closed without merging**
