### PR TITLE
added link (adds enhancement #596)

### PR DESCRIPTION
**Pull request by Fabus1184**
## Checklist

* [x] Test your changes as thoroughly as possible before you commit them. Preferably, automate your test by unit/integration tests.
* [x] If this PR comes from a fork, please [Allow edits from maintainers](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)
* [x] Set a speaking title. Format: {task_name} (closes #{issue_number}). For example: Use logger (closes # 41)
* [ ] [Link your Pull Request to an issue](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) (if applicable)
* [x] Create Work In Progress [WIP] pull requests only if you need clarification or an explicit review before you can continue your work item.
* [x] Make sure that your PR is not introducing _unnecessary_ reformatting (e.g., introduced by on-save hooks in your IDE)
* [x] Make sure that your PR does not contain changes in strings.xml (see issue #332)
* [x] Make sure that your PR does not contain compiled sources (already set by the default .gitignore) and / or binary files

### CODE REVIEW

**Comment by harambasicluka** [comment]
Hi @Fabus1184 ,

thank's for your contribution! :) But unfortunately we can't include this enhancement, this files are provided to us and we aren't allowed to change them. Nevertheless I'll forward this enhancement to the appropriate persons. 

Cheers,
Luka

**Comment by Fabus1184** [comment]
Ok, well can we add a button to open this pdf at the end of the activity heading when viewing the file in the app ?

**Comment by corneliusroemer** [comment]
It's a bit of a stretch to call adding a link "changing" the documents.

**Comment by Fabus1184** [comment]
> It's a bit of a stretch to call adding a link "changing" the documents.

I already created a pull request for a floating button to print the document when you view it

**Pull request closed without merging**
