### PR TITLE
Cannot delete tests older than 21 days - DE: Tests die älter als 21 Tage sind, können nicht gelöscht werden (EXPOSUREAPP-2398)

### LINKED ISSUE #1084: Can’t access test results b/c CWA is stuck at “Datenabruf”
## Avoid duplicates
Checked. It is not entirely clear currently whether this is Android exclusive, but as it happened under Android I've opened the issue here. If it turns out to also affect iOS, feel free to move this issue to the documentation repo.

## Describe the bug
This is an issue @kira99 experienced for the first time yesterday (26.08). 
On August 4th she got tested at "Rastanlage Donautal-Ost an der A3 bei Passau", scanned the QR code with CWA and [never received her results](https://github.com/corona-warn-app/cwa-documentation/issues/400#issuecomment-670972942).
Since then she has left the test in CWA and yesterday noticed that she cannot access her test anymore, instead this area now says 
>    Datenabruf...
>    ⚫ Das Ergebnis wird aktualisiert

And the wheel keeps spinning indefinitely.

## Expected behaviour
Ability to access (and delete) ones stored test and therefore no indefinitely spinning wheel in the area where tests can be added on the main screen. 

## Steps to reproduce the issue
See description.

## Technical details

- Mobile device: Xiaomi Redmi Note 7
- Android version: 10
- CWA 1.2.1

## Additional context
Just guessing from the indefinitely spinning wheel symptom and the timing this could be related to: https://github.com/corona-warn-app/cwa-app-android/issues/1063 and https://github.com/corona-warn-app/cwa-app-android/issues/967#issuecomment-680019497.

Internal Tracking ID: EXPOSUREAPP-2398

### PR DESCRIPTION
**Pull request by kolyaopahle**
### Description

This PR adds a new test status card to the homescreen to display when a test is older than 21 days and cant be requested from the backend anymore.
image
Pressing the card or the button will open the following dialog
image

### Steps to reproduce
1. Aquire an expired test and scan its qr code
2. Navigate to the homescreen

### CODE REVIEW

**Review by harambasicluka — APPROVED** [review]

**Review by harambasicluka — APPROVED** [review]

**Review by ralfgehrer — APPROVED** [review]
works nicely

**Review by SabineLoss — APPROVED** [review]

**Comment by vaubaehn** [comment]
@kolyaopahle 
Hi Kolya, do you have any idea why the fix doesn't seem to work in production for previuosly affected users?
The mood of some in #1084 after update  to 1.6.0 is a little bit complicated right now...
Kind regards, v.

**Comment by MikeMcC399** [comment]
#1084 is flagged as a hot topic and it would be good for the Open Source Team to respond urgently to the issues remaining in V1.6.0.

**Comment by Kolpa** [comment]
I've started discussion in #1084 again, as this issue still seems to be caused by something else. Thanks for the heads up :)

**Comment by kolyaopahle** [comment]
I've reopened discussion in #1084 as this indeed does not seem to fix the underlying issue that people are having in production. Thank you for the heads up :)

**Pull request merged**
