### PR TITLE
Fix for switches not working on slide (Fixes #607)

### LINKED ISSUE #607: Settings switches don't work when sliding them
## Describe the bug

When you slide a switch in the app settings, the option doesn't change.

## Expected behaviour

When sliding a switch in the app settings the option should change.

## Steps to reproduce the issue

Go into the apps settings, to notifications or tracing.
Instead of clicking the switch, drag / slide it manually with your finger.
See that the option did not change.

## Technical details

OnePlus 7 Pro OxygenOS 10 (Android 10)
App version 1.0.0

## Possible Fix

Add an additional listener, I'll look into it.

### PR DESCRIPTION
**Pull request by kolyaopahle**
## Checklist

* [ ] Test your changes as thoroughly as possible before you commit them. Preferably, automate your test by unit/integration tests.
* [ ] If this PR comes from a fork, please [Allow edits from maintainers](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)
* [ ] Set a speaking title. Format: {task_name} (closes #{issue_number}). For example: Use logger (closes # 41)
* [ ] [Link your Pull Request to an issue](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) (if applicable)
* [ ] Create Work In Progress [WIP] pull requests only if you need clarification or an explicit review before you can continue your work item.
* [ ] Make sure that your PR is not introducing _unnecessary_ reformatting (e.g., introduced by on-save hooks in your IDE)
* [ ] Make sure that your PR does not contain changes in strings.xml (see issue #332)
* [ ] Make sure that your PR does not contain compiled sources (already set by the default .gitignore) and / or binary files

## Description
This PR enables switch components to be toggled by swiping instead of only during click interaction.

### CODE REVIEW

**Comment by harambasicluka** [comment]
@kolyaopahle that's not possible due to some strange behaviours regarding accessibility. If you test this with talkback and a click works we can put it in.

**Comment by tomjschwanke** [comment]
Can we have both? An `onCheckedChangeListener` **and** an `onClickListener`?

**Comment by harambasicluka** [comment]
So optimal result would be:

- a clickable row
- a clickable switch
- a switchable switch :D

But all this has to work with google talkback without creating invalid states. I would be happy to include this if you're able to handle this requirements. Also see #466 with a more detailed answer.

Cheers,
Luka

**Comment by tomjschwanke** [comment]
grafik

The `onCheckedChangeListener` seems to generate a Touch-target. 
I scanned it with the App "Accessibility Scanner by Google, Orange rectangles are touch targets. Background is black, as the app forbids screenshots

**Comment by harambasicluka** [comment]
As #466 will be merged in the next days I looked into this PR again.

The proposed solution works for a user without a disability, but if you replace the `onCheckedChangeListener` the switch can be toggled via TalkBack but the listener isn't triggered. So I tried both `onCheckedChangeListener` and `onClickListener` this works fine with Talkback, but for the users without TalkBack both listeners are triggered.

@kolyaopahle could you look into it?

**Review by harambasicluka — APPROVED** [review]
💯

**Pull request merged**
