### PR TITLE
Make entire SettingsRow toggle the setting (closes #455)

### LINKED ISSUE #455: [UX] Increase touch target for switches
switches (3)

## Current Implementation

Currently if the user wants to change a setting that includes a `switch` he has to click **on the switch** (see red rectangel in the picture)

## Suggested Enhancement

From a usability/user experience point of view it would be better to "just tap somewhere where the text is" (green rectangle). This behaviour can be seen in the android settings or the Google Play Stores _Notifications_ settings. So the user knows (and maybe also expects) this behaviour

## Expected Benefits

Easier and more convenient way of "switching" some settings.

### PR DESCRIPTION
**Pull request by realcatgirly**
fixes #455 

## Checklist

* [x] Test your changes as thoroughly as possible before you commit them. Preferably, automate your test by unit/integration tests.
* [x] If this PR comes from a fork, please [Allow edits from maintainers](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)
* [x] Set a speaking title. Format: {task_name} (closes #{issue_number}). For example: Use logger (closes # 41)
* [x] [Link your Pull Request to an issue](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) (if applicable)
* [x] Create Work In Progress [WIP] pull requests only if you need clarification or an explicit review before you can continue your work item.
* [x] Make sure that your PR is not introducing _unnecessary_ reformatting (e.g., introduced by on-save hooks in your IDE)
* [x] Make sure that your PR does not contain changes in strings.xml (see issue #332)
* [x] Make sure that your PR does not contain compiled sources (already set by the default .gitignore) and / or binary files

## Description

#455 mentioned the settings being only toggleable by hitting the switch. This PR makes the entire SettingsRow toggle the switch, making it behave like stock Android settings.

### CODE REVIEW

**Comment by tomjschwanke** [comment]
This would need to be remembered for all settings added in the future

**Comment by tomjschwanke** [comment]
Todo: maybe fix the animation, stock Android has a little animation, filling the box from where you tapped, in the current implementation, it lights up the entire box immediately

**Comment by tomjschwanke** [comment]
Edit: should've probably proposed this PR to dev instead of master.

Can't change it now, should I make a new one proposing this to dev?

**Comment by ironjan** [comment]
@tomjschwanke  you should be able to change the base branch as described on
https://github.blog/2016-08-15-change-the-base-branch-of-a-pull-request/

**Comment by tomjschwanke** [comment]
Now there are a lot of unrelated commits in this PR, should I make a new PR coming from my forks dev branch.

**Pull request closed without merging**
