### PR TITLE
Survey Consent Details Screen (EXPOSUREAPP-5055)

### PR DESCRIPTION
**Pull request by LukasLechnerDev**
This PR includes:

- The new Survey Consent **Detail** Screen
- An update of the Survey Consent Screen according to the current figma designs

### CODE REVIEW

**Review by BMItr — DISMISSED** [review]
nice 👌

**Review by janetback — DISMISSED** [review]
UA reviewed

**Review by BMItr — DISMISSED** [review]

**Review by janetback — DISMISSED** [review]
UA reviewed

**Review by kolyaopahle — DISMISSED** [review]
👍 LGTM, pls fix the string errors

**Review by BMItr — APPROVED** [review]

**Review by kolyaopahle — APPROVED** [review]

**Pull request merged**
