### PR TITLE
Fix keyboard issue when editing contact journal entries (EXPOSUREAPP-5869)

### PR DESCRIPTION
**Pull request by ralfgehrer**
Also addresses: EXPOSUREAPP-5749, EXPOSUREAPP-5914

Tested on Pixel (Android 10) and Samsung A3 (Android 7.0)

**Steps:**
- Create a person in contact journal
- Edit Name of that person
- go back to "Edit People" screen
- Try to edit name again of the same person
- keyboard should appear on first attribute (Name)

**Expected result:**
- Keybord should appear and cursor should be at the end of the  name field entry of a person  (same for location) so one can continue writing

### CODE REVIEW

**Comment by MikeMcC399** [comment]
I successfully tested this fix on:
- Pixel 3a Android 11 emulator
- Samsung Galaxy A5 (2017) Android 8.0.0

With 1.14.3 on the Pixel device the keyboard failed to display the second time.
On the A5 with Android 8 the keyboard did not even appear the first time.

Both these issues are no longer occurring with this fix. 👍🏻

This corresponds to issue https://github.com/corona-warn-app/cwa-app-android/issues/2658#issuecomment-803650687.

**Review by harambasicluka — COMMENTED** [review]
Works as expected. Tested on a OnePlus 8/Android 11.

But I fear that this will cause some trouble with Google Talkback. Will test it on a Pixel 3. -> @axelherbstreith could you also have a look?

**Review by harambasicluka — CHANGES_REQUESTED** [review]
I think we need to check this with our accesibility colleagues, if i go to the screen I only get an announcement for the keyboard but nothing else. IMHO we should get an announcement for the screen than for the focused input field and then for the keyboard.

I currently have some trouble with my Pixel 3, so I also tested it on my OnePlus.

**Comment by axelherbstreith** [comment]
@harambasicluka @ralfgehrer tested it on my Samsung Galaxy S8. For me, the screen announcement is 100% identical to version without the bug fix. 

The issue that the screen itself is not announced is due to the fact that the focus changes to the text box "Name" immediately after opening the the screen. Therefore Talkback stops announcing the screen and starts announcing the text box itself. I personally would clarify this with the accessibility colleagues since as far as I can tell, this is not directly a bug.

**Review by axelherbstreith — APPROVED** [review]

**Review by harambasicluka — APPROVED** [review]
@axelherbstreith thanks for testing it also on an older version. So the problem wasn't introduced here 👍

**Pull request merged**
