### PR TITLE
Fix qr code being cut off (fixes #2852) (COMMUNITY)

### LINKED ISSUE #2852: QR code in organizer_qr_code_detail has cut off corners when filling in max event detail length
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: Nexus 5X
- Android version: 8.1
- App version: 2.0.2

## Describe the bug

When you fill in event description and location to max length when generating a QR code and display the result on a Nexus 5X, the QR code has cut-off corners and is less likely to scan correctly on various devices.

image
image

(sorry about the CCTG branding, this should reproduce with CWA just as well)

## Steps to reproduce the issue
1. Create QR Code
2. + QR Code
3. select any category
4. Fill in words into the description until you hit the limit, same for the Place field
5. Save and open the QR code for scanning
6. See cut-off corners

## Expected behaviour

QR code is not cut off

## Possible Fix

```diff
--- a/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/eventregistration/organizer/details/QrCodeDetailFragment.kt
+++ b/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/eventregistration/organizer/details/QrCodeDetailFragment.kt
@@ -138,7 +138,7 @@ class QrCodeDetailFragment : Fragment(R.layout.trace_location_organizer_qr_code_
                     binding.progressBar.hide()
                     binding.qrCodeImage.apply {
                         val resourceId = RoundedBitmapDrawableFactory.create(resources, it)
-                        resourceId.cornerRadius = it.width * 0.1f
+                        resourceId.cornerRadius = 15f
                         setImageDrawable(resourceId)
                     }
                 }
```

## Additional context

---
Internal Tracking ID: [EXPOSUREAPP-6540](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6540)

### PR DESCRIPTION
**Pull request by Bubu**
This was causing starkly rounded corners for bigger qr codes which had
trouble being scanned.

Fixes #2852.

### Description

This sets the rounded corner radius to that of the backgound image.

Result (compare to #2852):

image

### Steps to reproduce

See #2852

---
Internal Tracking ID: [EXPOSUREAPP-6540](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6540)

### CODE REVIEW

**Comment by Bubu** [comment]
I intentionally targeted 2.0 with this. It would be nice if it were to make the initial presence tracing release :-).

**Review by fm-sys — DISMISSED** [review]
LGTM!

**Comment by harambasicluka** [comment]
@Bubu thanks for this fix, sadly we can't include anything in `release/2.0.x`. Please target `release/2.1.x`.

**Review by axelherbstreith — DISMISSED** [review]
Nice fix 👍

**Comment by Bubu** [comment]
Rebased on 2.1.x. I hope I didn't mess something up now.

**Comment by harambasicluka** [comment]
Thanks! :)

**Review by harambasicluka — APPROVED** [review]

**Review by axelherbstreith — APPROVED** [review]

**Pull request merged**
