### PR TITLE
Prettify svg templates for pdf export (EXPOSUREAPP-13635)

### LINKED ISSUE #5356: Extra whitespace in EU printout
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [ ] Bug is not already reported in another issue
Refer also to https://github.com/corona-warn-app/cwa-app-android/issues/5350, which is marked with label https://github.com/corona-warn-app/cwa-app-android/labels/Fix%202%2E25.

## Technical details

- Device name: Pixel 3a emulator
- Android version: 12
- App version: pre-release [2.25.x - 2.25.0-RC1](https://github.com/corona-warn-app/cwa-app-android/tree/release/2.25.x) in addition to previously reported 2.24.2.
Regression from CWA 2.23.2.

## Describe the bug

The EU printout contains extraneous whitespace:

- between the introductory words of each paragraph and the following text
- between the first part of a hyphenated word and the hyphen
- after the link https://reopen.europa.de before the full-stop 

CWA 2 25 x export cert

## Steps to reproduce the issue

On Desktop

1. Use Android Studio Device File Explorer to transfer vaccination certificate PDF to the emulator

In CWA App

2. Tap Scan
3. Tap Open File
4. Navigate to vaccination certificate in File app and tap on file, tap "Continue"
5. Tap three-dot symbol
6. Select Display Print Version, tap "Next"
7. Tap Printer symbol
8. Select printer "Save as PDF", tap "SAVE"
9. Open "Files" app
10. Navigate to previously saved PDF and tap to open
11. Use Ctrl and mouse key to zoom to information section
12. Rotate right twice using emulator controls (for convenience in reading)

Note the gaps in the text as shown in the marked-up screenshot.

## Expected behavior

An exported certificate should not contain unsightly whitespace in the information section.

## Possible Fix

Review creation of exported certificate from template.

## Additional context

- The template [de_vc_v4.1.svg](https://github.com/corona-warn-app/cwa-app-android/blob/release/2.25.x/Corona-Warn-App/src/main/assets/template/de_vc_v4.1.svg) viewed on its own in Google Chrome shows no whitespace gaps.

- Since the template places the text using absolute coordinates, there may be a scaling issue involved. 

- This problem has also been reported for the CovPass App in https://github.com/Digitaler-Impfnachweis/covpass-android/issues/222.

---
Internal Tracking ID: [EXPOSUREAPP-13635](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13635)

### PR DESCRIPTION
**Pull request by schauersbergern**
[Ticket](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13635)

Testing:

Scan following EU and non EU certificates:

cwa tc gen -e wru -o --seed 10 --iss AT -s t.0.co=AT --png
cwa vc gen -e wru -o --seed 10 --iss AT -s v.0.co=AT --png
cwa rc gen -e wru -o --seed 10 --iss AT -s r.0.co=AT --png
cwa tc gen -e wru -o --seed 10 --png
cwa vc gen -e wru -o --seed 10 --png
cwa rc gen -e wru -o --seed 10 --png

- Trigger batch export and check if text looks good now
- Export Certificates and check if text looks good now
- Export pdf per Mail and check if text looks good now

Tested in Emulator, Pixel 6 and Samsung A3 where text looked good now

### CODE REVIEW

**Comment by MikeMcC399** [comment]
I can still see white space between the hyphenated words and the hyphen.

image

- Related to issue https://github.com/corona-warn-app/cwa-app-android/issues/5356

**Comment by schauersbergern** [comment]
> I can still see white space between the hyphenated words and the hyphen.
> 
> image
> 
> * Related to issue [Extra whitespace in EU printout #5356](https://github.com/corona-warn-app/cwa-app-android/issues/5356)

@MikeMcC399 hyphens are fixed in new recent commit

**Comment by MikeMcC399** [comment]
@schauersbergern 

> hyphens are fixed in new recent commit.

I checked by exporting a German vaccination certificate and the hyphens now look fine. 👍🏻
That is the only file which I can check.

**Review by SamuraiKek — APPROVED** [review]
Text looks good now.

**Pull request merged**
