### PR TITLE
Add transition to Contact Journal onboarding fragment (COMMUNITY)

### LINKED ISSUE #2952: Different animations for different onboarding info screens
### Describe the bug

The Check-In onboarding screen has an animation while the Contact Journal onboarding does not.

https://user-images.githubusercontent.com/16943720/115985591-cb60aa80-a5ac-11eb-9fad-fab905de90e2.mp4

### Steps to reproduce the issue

Open Check-In screen and Contact Journal screen on fresh installations.

### Possible Fix

Add animation to Contact Journal onboarding screen. #2954

----
Internal Tracking-ID: [EXPOSUREAPP-6763](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6763)

### PR DESCRIPTION
**Pull request by fynngodau**
This PR fixes #2952 and increases consistency between the two screens by adding a transition to the Contact Journal onboarding fragment.

Video demonstration:

https://user-images.githubusercontent.com/16943720/115985885-20e98700-a5ae-11eb-865d-d6ed95fc55d0.mp4

----
Internal Tracking-ID: [EXPOSUREAPP-6763](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6763)

### CODE REVIEW

**Comment by mtwalli** [comment]
@fynngodau Thank you! for adding the transition. We have to make one more adjustment to have consistent with the Check-Ins.

1- in `contact_diary_overview_fragment.xml` please set background colour as `android:background="@color/colorBackground"`

2- in `ContactDiaryOverviewFragment` please add 
```kotlin
 override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        exitTransition = MaterialSharedAxis(MaterialSharedAxis.Z, true)
        reenterTransition = MaterialSharedAxis(MaterialSharedAxis.Z, false)
    }
```

So we will have the consistent transitions when the information screen is also accessed from overflow menu as in

https://user-images.githubusercontent.com/25054729/116070924-79438600-a68d-11eb-911b-ad89e4bc1db7.mp4

**Comment by fynngodau** [comment]
@mtwalli Great find! Added to PR.

**Review by mtwalli — APPROVED** [review]
Thanks

**Review by axelherbstreith — APPROVED** [review]
Looks good 👍

**Pull request merged**
