### PR TITLE
Remove sqlcipher  (DEV)

### PR DESCRIPTION
**Pull request by mtwalli**
⬆️

### CODE REVIEW

**Review by d4rken — DISMISSED** [review]
lgtm

**Review by BMItr — DISMISSED** [review]
👌 thx for cleaning up

**Comment by vaubaehn** [comment]
Didn't check yet, but in case there are no other zetetic dependencies, this (and many following lines) may also be taken out?
https://github.com/corona-warn-app/cwa-app-android/blob/6e281ebfadbb1d945bcff5dc545289b16335b36a/Corona-Warn-App/src/main/assets/technical.html#L114

**Comment by mtwalli** [comment]
> Didn't check yet, but in case there are no other zetetic dependencies, this (and many following lines) may also be taken out?
> 
> https://github.com/corona-warn-app/cwa-app-android/blob/6e281ebfadbb1d945bcff5dc545289b16335b36a/Corona-Warn-App/src/main/assets/technical.html#L114
@vaubaehn Thanks for point this out, I updated the file

**Review by BMItr — APPROVED** [review]
still lgtm

**Pull request merged**
