### PR TITLE
Fix button shadows (COMMUNITY)

### PR DESCRIPTION
**Pull request by fynngodau**
This addresses the problem described in #2856.

Demonstration:

Screenshot_1619264002 | Screenshot_1619264011
---|---

It works by telling parents not to clip their children to its padding through `clipToPadding="false"`. At first, I thought this would require restructuring each affected layout, and was happy to learn that this is not the case and that the fix is so simple.

---
 Internal Tracking ID: [EXPOSUREAPP-6543](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6543)

### CODE REVIEW

**Comment by dsarkar** [comment]
@fynngodau Thanks.  Internal Tracking ID: [EXPOSUREAPP-6543](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6543)

---
Corona-Warn-App Open Source Team

**Comment by harambasicluka** [comment]
@fynngodau I just checked our mockups, our buttons shouldn't have a shadow O.o
Here is an example from the mockups:
image

So I would suggest to close this PR and if you want to fix it remove the shadow from our button styling.

**Comment by fynngodau** [comment]
@harambasicluka Does that apply to all of the buttons? For the button on the card (which is already elevated itself), that makes sense, but for other buttons, in my opinion they really should have a shadow to look Material.

**Comment by harambasicluka** [comment]
@fynngodau I think that are personal preferences. Also Google mentions that a high contrast is enough: https://material.io/design/environment/elevation.html#depicting-elevation
image

This would be a question to our designers, so if you want I can forward your suggestion to our designers. But for now I would say this PR solves a problem which shouldn't be there as our buttons shouldn't have an elevation. So I would still stick to my initial suggestion :)

**Pull request closed without merging**
