### PR TITLE
Use vector drawables support library (COMMUNITY)

### PR DESCRIPTION
**Pull request by fynngodau**
### Description

Set `vectorDrawables.useSupportLibrary = true` in `build.gradle`.

This causes the Android build system not to pregenerate all image resources for different sizes, thereby drastically reducing APK size.

To avoid crashes, additionally:

* pregenerate the splash screen logo
* always use `app:srcCompat` instead of `android:src`

### Steps to reproduce

Compile APK with and without these changes and compare `res` folder.

To the left: CWA build without support library for vector drawables; to the right: CWA build with support library for vector drawables.

image

How to test: ensure nothing breaks.

If you know any reason that speaks against setting this, please let me know.

### Related issues

https://github.com/corona-warn-app/cwa-app-android/issues/265#issuecomment-757444223
#482

### CODE REVIEW

**Comment by fynngodau** [comment]
The pre-generated PNGs are not generated correctly, even: for instance, this is a pre-generated PNG from the latest official release APK (1.15.2 `/res/drawable-mdpi-v4/ic_information_illustration_technical.png`):

ic_information_illustration_technical

**Comment by MikeMcC399** [comment]
@fynngodau 
This issue is also mentioned in https://github.com/corona-warn-app/cwa-app-android/issues/265#issuecomment-757444223 with Internal tracking ID EXPOSUREAPP-1968. Maybe you could cross-check if you would also be fixing this one?

**Comment by fynngodau** [comment]
I noticed this required two more changes:

* pregenerating the splash screen logo, because Android 6 does not want to render it itself (probably)
* always use `app:srcCompat` instead of `android:src`

I added the according changes and changed the base to `release/2.1.x`. I could not find any further crashes on Android 6 or otherwise.

@MikeMcC399 Indeed, that issue is related. It should be fixed with this PR because the assets would no longer be incorrectly pre-generated, but instead be rendered on the device (and, I believe, correctly).

**Review by mtwalli — DISMISSED** [review]
@fynngodau thank you very much!, this PR hits  two birds with one stone 😃.
it did reduce the APK size significantly 

From:
Screenshot 2021-04-10 at 23 38 16

To:
Screenshot 2021-04-10 at 23 00 58

Additionally fixes the linked issues above for older versions.


FYI splash icon uses Vector Drawable gradient as `fillColor` which is only supported from API 24+, that's why you had to bundle the icons manually.  While this is a downside of this approach , I don't think it is a big deal for one icon considering the benefits, and I don't expect that the logo icon will change any time soon.

**Comment by fynngodau** [comment]
@mtwalli Thanks for this insightful information :heart:

**Review by d4rken — APPROVED** [review]
lgtm

**Review by mtwalli — APPROVED** [review]

**Comment by d4rken** [comment]
Thank you @fynngodau

**Pull request merged**
