### PR TITLE
Update automatic screenshot behaviour for statistics (EXPOSUREAPP-4622)

### PR DESCRIPTION
**Pull request by jurajkusnier**
Take screenshots of statistics cards with current data

### Testing:
```bash
install fastlane
run ./gradlew clean assembleDebug assembleAndroidTest
run bundle exec fastlane screengrab
```

### CODE REVIEW

**Review by ralfgehrer — APPROVED** [review]
LGTM

**Review by LukasLechnerDev — APPROVED** [review]
Good Work! 

One small thing I found was that some cards are not aligned in the center:

HomeFragment_statistics_card_1_1611752640135

**Comment by jurajkusnier** [comment]
> Good Work!
> 
> One small thing I found was that some cards are not aligned in the center:
> 
> HomeFragment_statistics_card_1_1611752640135

Do you mean aligned vertically or horizontally? I use `RecyclerViewScrollAction` for scrolling that is used also for other screenshots.

**Comment by LukasLechnerDev** [comment]
I mean horizontally. If I use the app normally, they "snap" at a central position.

**Pull request merged**
