### PR TITLE
UQS in BottomBar (EXPOSUREAPP-9498)

### PR DESCRIPTION
**Pull request by mtwalli**
Feature branch 

## Ticket
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9498

### CODE REVIEW

**Review by InkenTownsend — DISMISSED** [review]
UA approved

**Review by AlexanderAlferov — APPROVED** [review]
What a fancy feature and implementation!  Thank you 🚀

**Comment by BMItr** [comment]
image
works very nice 👌

**Comment by BMItr** [comment]
one optional comment:
if you press too quick again(twice) the "ScanQR" Button, multiple instances of the scan fragment are opened (and have to be closed later).
As some people might have "shaky fingers" its worth to prevent I think.
Buts its just a cherry..

**Review by BMItr — APPROVED** [review]

**Comment by mtwalli** [comment]
> one optional comment: if you press too quick again(twice) the "ScanQR" Button, multiple instances of the scan fragment are opened (and have to be closed later). As some people might have "shaky fingers" its worth to prevent I think. Buts its just a cherry..

Makes total sense , I will create a fix for that in a follow up PR

**Pull request merged**
