### PR TITLE
Wrong button text color in symptom flow (EXPOSUREAPP-4207)

### PR DESCRIPTION
**Pull request by AndroidMedaGalaxy**
### Description

Text colors in symptom flow are fixed

### Steps to reproduce
Scan a positive QR code. Give consent and proceed to symtoms from thank you screen
Observe

### Screenshot

Contains both default and night themes stick with it till the end
text color change

### CODE REVIEW

**Comment by ralfgehrer** [comment]
Please rebase one 1.11.x

**Comment by AlexanderAlferov** [comment]
Tested on Samsung S8:
Screenshot 2020-12-18 at 13 39 45


Probably need to adjust calendar header too.

**Comment by chiljamgossow** [comment]
Adapted day and night mode for consistency and high contrast

**Comment by chiljamgossow** [comment]
device-2020-12-23-084317
device-2020-12-23-084335
device-2020-12-23-084402
device-2020-12-23-084347

**Review by chiljamgossow — APPROVED** [review]

**Review by ralfgehrer — APPROVED** [review]
Tested on Pixel in light and dark mode.

**Pull request merged**
