### PR TITLE
Added autoLink to layouts (closes issue #633)

### LINKED ISSUE #633: URIs/URLs/links in texts not active
## Describe the bug
Almost all texts in the "App-Informationen" menu (some of which are also displayed when the app is started for the first time) include URIs, email addresses, phone numbers. These can not be opened directly.

On top of this, in "Nutzungsbedingungen" there is also a text "[Link]" without a URI.

## Expected behaviour
URIs must be active/clickable.

## Steps to reproduce the issue
Open e.g. the "Nutzungsbedingungen" and try to open one of the links or try to send an email to one of the email addresses listed in those texts.

## Possible Fix
Make https links, email addresses and possibly also phone numbers within those texts clickable/active.

## Additional context
As it is now, URIs need to be either memorized or written down on a piece of paper, then typed into the phone's browser. This is completely unacceptable form a user's point of view.

### PR DESCRIPTION
**Pull request by eliaszemanek**
## Checklist

* [x] Test your changes as thoroughly as possible before you commit them. Preferably, automate your test by unit/integration tests.
* [x] If this PR comes from a fork, please [Allow edits from maintainers](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)
* [x] Set a speaking title. Format: {task_name} (closes #{issue_number}). For example: Use logger (closes # 41)
* [x] [Link your Pull Request to an issue](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) (if applicable)
* [x] Create Work In Progress [WIP] pull requests only if you need clarification or an explicit review before you can continue your work item.
* [x] Make sure that your PR is not introducing _unnecessary_ reformatting (e.g., introduced by on-save hooks in your IDE)
* [x] Make sure that your PR does not contain changes in strings.xml (see issue #332)
* [x] Make sure that your PR does not contain compiled sources (already set by the default .gitignore) and / or binary files

## Description

Added autoLink in fragment_information_legal.xml, fragment_information_contact and include_information_details.xml.

It's a nice little improvement to easily call, write or visit a telephone number, an email or a website  to the given information. With on click the telephone app, the mail app or the browser will start.

### CODE REVIEW

**Comment by harambasicluka** [comment]
Hi @eliaszemanek ,

thanks for your contribution! :) We are currently investigating internally if that's a wanted behaviour. I'll come back to you if we have decision.

Thanks,
Luka

**Review by harambasicluka — APPROVED** [review]
Hi @eliaszemanek ,
thanks for your patience! 💯

**Review by harambasicluka — CHANGES_REQUESTED** [review]
The link color doesn't match our tint color.

@eliaszemanek could you change the color of the links to `colorTextTint`?

image

If not let me know :)

Cheers,
Luka

**Comment by eliaszemanek** [comment]
Hi @harambasicluka 

I changed the textColor to colorTextTint

Screenshot_1593168791

Cheers,
Elias

**Review by harambasicluka — APPROVED** [review]
That was quick! Thanks 👍

**Pull request merged**
