### PR TITLE
Set up and configure fastlane to take screenshots - Home Screen(EXPOSUREAPP-2950)

### PR DESCRIPTION
**Pull request by mtwalli**
1- Add screenshot tests for Home Screen
2- Create a screenshot shell script to run `screengrab` and zip screenshots afterward

Enhancement: Added delay time of 2 sec before every screenshot statement to avoid blank screens

Aside from the ticket:
1- Fixed crash in DI that was happening for UI tests on pre-Android 11 API `onPreCreateActivity` was not called for all versions
2- Fixed Images are not showing in UI tests for some cards in Home Screen (This might be a topic for our Tech talk)
    [Vector Drawable](https://developer.android.com/guide/topics/graphics/vector-drawable-resources#vector-drawables-backward-solution)

### Testing:
1. run `./gradlew clean assembleDebug assembleAndroidTest` for clean state
2. run `bash screenshot.sh` in case there is APK already built using the command in point 1 you can start from here.

Screenshots and screenshots.zip are located under `fastlane/metadata/android`

### CODE REVIEW

**Comment by jurajkusnier** [comment]
what do you think about more descriptive naming? Not just "HomeFragment" but also app state like "submission done", "test negative/positive/invalid", etc?

**Comment by mtwalli** [comment]
> what do you think about more descriptive screenshots file naming? Not just "HomeFragment" but also app state like "submission done", "test negative/positive/invalid", etc?

Make sense to identify the screen's case when something is odd

**Review by jurajkusnier — DISMISSED** [review]

**Comment by ralfgehrer** [comment]
If I run it on my usual test device, the icon color is black instead of white.


HomeFragment_test_error_1610530272705


HomeFragment_submission_done_1610530305941

**Comment by mtwalli** [comment]
> If I run it on my usual test device, the icon color is black instead of white.
> 
> HomeFragment_test_error_1610530272705
> 
> HomeFragment_submission_done_1610530305941

Thx, fixed

**Review by ralfgehrer — APPROVED** [review]

**Review by jurajkusnier — APPROVED** [review]

**Pull request merged**
