### PR TITLE
Update mapping of app config (EXPOSUREAPP-10446)

### PR DESCRIPTION
**Pull request by jurajkusnier**
## Jira Link
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10238

### CODE REVIEW

**Comment by vaubaehn** [comment]
@jurajkusnier 
Thanks for working on this. Do you have any idea what is a realisitc number of additional entries to the app config, especially when other EU countries add a long range of entries? Do you expect any impact on performance, especially for old mobiles?
/cc: @mlenkeit @thomasaugsten

**Comment by jurajkusnier** [comment]
> @jurajkusnier Thanks for working on this. Do you have any idea what is a realistic number of additional entries to the app config, especially when other EU countries add/provide a long range of entries? Do you expect any impact on performance, especially for old mobiles? /cc: @mlenkeit @thomasaugsten

We do not currently expect a long range of entries in the app config. So the impact on performance should be minimal even for old devices.

**Review by mtwalli — APPROVED** [review]

**Comment by vaubaehn** [comment]
Hi  @jurajkusnier , thanks for your reply! Fingers crossed 🤞  - have a good week!

**Comment by mlenkeit** [comment]
> @jurajkusnier Thanks for working on this. Do you have any idea what is a realistic number of additional entries to the app config, especially when other EU countries add/provide a long range of entries? Do you expect any impact on performance, especially for old mobiles? /cc: @mlenkeit @thomasaugsten

@vaubaehn this is not designed to be a permanent solution. There are parallel works going on on EU level for a more scalable solution.

**Comment by vaubaehn** [comment]
> @vaubaehn this is not designed to be a permanent solution. There are parallel works going on on EU level for a more scalable solution.

@mlenkeit thanks for the information. Sounds interesting!

**Pull request merged**
