### PR TITLE
Notification to open app from time to time comes back every few minutes (EXPOSUREAPP-4623)

### PR DESCRIPTION
**Pull request by kolyaopahle**
changed ExistingPeriodicWorkPolicy to KEEP for deadman check task to stop notification loop on every app open

### Steps to reproduce
1. launch app without having done an exposure check in the last 35 hours (or set delay in de/rki/coronawarnapp/deadman/DeadmanNotificationScheduler.kt:22 to 0L)
2. wait for notification
3. open app via notification
4. a new notification should only appear after one hour or more not within minutes

### CODE REVIEW

**Comment by ralfgehrer** [comment]
According to the ticket, this should go into 1.12. instead

**Comment by kolyaopahle** [comment]
> According to the ticket, this should go into 1.12. instead

whoops, changed base and rebased commits

**Comment by d4rken** [comment]
Can you elaborate on why the `REPLACE` causes it, and the `KEEP` fixes the behavior?

**Comment by kolyaopahle** [comment]
Currently the app schedules a check for the deadman notification with a periodic worker that will check how long the last successful submission is in the past and will schedule a new one time worker with a run delay of the difference of that time and 35 hour's

If the last check was run more than 35 hours ago a one time worker to display the notification is scheduled immediately.

The periodic worker is scheduled on each app launch, which results in a run of the worker on each app start wenn using the REPLACE option, which in turn results in a scheduling of the one time worker to display the notification, which will keep you in the feedback loop.

Previously if you swiped away the notification you would also observe the 1 notification per hour behavior but opening the app via the notification would result in the notification spam

**Comment by d4rken** [comment]
@kolyaopahle Thanks for the explanation. This to be an important part of the deadman mechanism, would it be possible to add a shorter explanation as comment to the code where the worker is setup?

**Comment by kolyaopahle** [comment]
> @kolyaopahle Thanks for the explanation. This seems to be an important part of the deadman mechanism, would it be possible to add a shorter explanation as comment to the code where the worker is setup?

Done :)

**Review by AlexanderAlferov — APPROVED** [review]
LGTM 🚀

**Review by d4rken — APPROVED** [review]

**Comment by MikeMcC399** [comment]
Link to #2093.

**Pull request merged**
