### PR TITLE
Update certlogic-android (DEV)

### PR DESCRIPTION
**Pull request by d4rken**
Update to https://github.com/corona-warn-app/dgc-certlogic-android/releases/tag/cwa-1.0.0-38-07d0d32e

### CODE REVIEW

**Comment by mtwalli** [comment]
I think https://github.com/corona-warn-app/cwa-app-android/pull/3695 needs to be merged  first

**Comment by harambasicluka** [comment]
We might skip this update until https://github.com/eu-digital-green-certificates/dgc-certlogic-android/issues/36 is fixed.
CC: @mlenkeit

**Comment by mlenkeit** [comment]
Yes, please hold back with this update until https://github.com/eu-digital-green-certificates/dgc-certlogic-android/issues/36 is fixed. I think the latest changes to upstream anyway don't contain any relevant changes.

**Comment by vaubaehn** [comment]
FYI https://github.com/eu-digital-green-certificates/dgc-certlogic-android/pull/38

**Review by chiljamgossow — APPROVED** [review]

**Review by mtwalli — APPROVED** [review]

**Pull request merged**
