### PR TITLE
Fixing text discrepancies (EXPOSUREAPP-4233)

### PR DESCRIPTION
**Pull request by AndroidMedaGalaxy**
### Description
Text adjusted 

### Screenshots

Risiko-Er
Risiko-Er2

### Steps to reproduce
1. Screen "Risiko-Ermittlung" -> Observe changes
2. Screen "Länderübergreifende Risiko-Ermittlung" -> Observe changes

### CODE REVIEW

**Review by ralfgehrer — CHANGES_REQUESTED** [review]
I suppose @janetback already updated the text. The bug was about introducing a new text block. 

"I have added all the text corrections. The only task left is to add the additional paragraph.
Could you or someone out of your team please take care of this? Thanks."

**Review by Oliver-Zimmerman — DISMISSED** [review]

**Review by janetback — DISMISSED** [review]
UA reviewed

**Comment by ritsam** [comment]
> I suppose @janetback already updated the text. The bug was about introducing a new text block.
> 
> "I have added all the text corrections. The only task left is to add the additional paragraph.
> Could you or someone out of your team please take care of this? Thanks."

The text block (new paragraphs) is performed here as well. But as there was already the PR #1844 existed (which is merged now) it has introduced conflicts. I'll rectify that now.

**Review by ralfgehrer — COMMENTED** [review]
@ritsam now the PR has zero changes. 
Please reach out to Janet and ask for clarification what text block needs to be added. Thank you.

**Review by janetback — CHANGES_REQUESTED** [review]
There is a small error in the first change I'm afraid - (settings_tracing_body_text): This section of the string:  

 "Die App lädt täglich eine Liste mit den Zufalls-IDs"

needs to be changed back to (minus a space, I believe:
 "Die App lädt täglich Listen mit den Zufalls-IDs"

Wie need the plural (Die App lädt täglich Listen mit den Zufalls-IDs', 
but we also need the sentence '...Schieberegler..' to be in a separate paragraph :-)
Thanks Rituraj

**Comment by ritsam** [comment]
> There is a small error in the first change I'm afraid - (settings_tracing_body_text): This section of the string:
> 
> "Die App lädt täglich eine Liste mit den Zufalls-IDs"
> 
> needs to be changed back to (minus a space, I believe:
> "Die App lädt täglich Listen mit den Zufalls-IDs"
> 
> Wie need the plural (Die App lädt täglich Listen mit den Zufalls-IDs',
> but we also need the sentence '...Schieberegler..' to be in a separate paragraph :-)
> Thanks Rituraj

Hi @janetback I believe I had updated it before but the recent merge conflicts might have caused it to vanish. updated it again. please check when you can.

**Review by janetback — APPROVED** [review]
UA approved

**Review by ralfgehrer — APPROVED** [review]

**Pull request merged**
