### PR TITLE
Move full name formatted to interface (EXPOSUREAPP-7824)

### PR DESCRIPTION
**Pull request by chiljamgossow**
Move logic for consistency

### CODE REVIEW

**Review by axelherbstreith — DISMISSED** [review]

**Review by mtwalli — APPROVED** [review]
Lgtm, thanks for refactoring

**Review by jurajkusnier — COMMENTED** [review]
I got NullPointerException during the testing, not sure if it's related to your changes
```
2021-07-29 11:21:27.637 12711-12789/de.rki.coronawarnapp.test E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-14 @coroutine#64
    Process: de.rki.coronawarnapp.test, PID: 12711
    java.lang.NullPointerException
        at de.rki.coronawarnapp.covidcertificate.test.core.storage.TestCertificateContainer$testCertificateQRCode$2.invoke(TestCertificateContainer.kt:30)
        at de.rki.coronawarnapp.covidcertificate.test.core.storage.TestCertificateContainer$testCertificateQRCode$2.invoke(TestCertificateContainer.kt:29)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at de.rki.coronawarnapp.covidcertificate.test.core.storage.TestCertificateContainer.getTestCertificateQRCode$Corona_Warn_App_deviceForTestersDebug(TestCertificateContainer.kt:29)
        at de.rki.coronawarnapp.covidcertificate.test.core.TestCertificateRepository$special$$inlined$combine$1$3.invokeSuspend(Zip.kt:340)
        at de.rki.coronawarnapp.covidcertificate.test.core.TestCertificateRepository$special$$inlined$combine$1$3.invoke(Unknown Source:13)
        at de.rki.coronawarnapp.covidcertificate.test.core.TestCertificateRepository$special$$inlined$combine$1$3.invoke(Unknown Source:6)
        at kotlinx.coroutines.flow.internal.CombineKt$combineInternal$2.invokeSuspend(Combine.kt:82)
        (Coroutine boundary)
       ```

**Comment by jurajkusnier** [comment]
It's not possible to open the CWA again after the NullPointerException. Crash during the app start.
```
2021-07-29 11:28:20.686 13549-13577/de.rki.coronawarnapp.test E/TestCertificateRepository: Certificate entry already exists for qrcode-PCR-E35DC9-E35DC93C-3B93-41DD-9CCD-8DE1430FE67C
2021-07-29 11:28:20.695 13549-13603/de.rki.coronawarnapp.test E/TestCertificateRetrievalScheduler: Creation trigger failed.
    de.rki.coronawarnapp.covidcertificate.common.exception.InvalidTestCertificateException: Certificate already registered.
        at de.rki.coronawarnapp.covidcertificate.test.core.TestCertificateRepository$requestCertificate$newData$1.invokeSuspend(TestCertificateRepository.kt:127)
        at de.rki.coronawarnapp.covidcertificate.test.core.TestCertificateRepository$requestCertificate$newData$1.invoke(Unknown Source:8)
        at de.rki.coronawarnapp.covidcertificate.test.core.TestCertificateRepository$requestCertificate$newData$1.invoke(Unknown Source:4)
        at de.rki.coronawarnapp.util.flow.HotDataFlow$internalProducer$1$invokeSuspend$$inlined$collect$1.emit(Collect.kt:145)
        at kotlinx.coroutines.flow.SharedFlowImpl.collect(SharedFlow.kt:351)
        at kotlinx.coroutines.flow.SharedFlowImpl$collect$1.invokeSuspend(Unknown Source:15)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

steps to reproduce:
1. clean install
2. change dev env to WRU
1. `cwa qr -r negative -e wru`
1. scan the code
1. refresh certificate 

please let me know if you can reproduce this issue or it's just my build

**Comment by chiljamgossow** [comment]
Crash is from release branch

**Review by jurajkusnier — APPROVED** [review]
the crash is not related to this PR :)

**Comment by MikeMcC399** [comment]
Link back to issue #3692.

**Pull request merged**
