### PR TITLE
Merge branch 1.8.x into 1.9.x (DEV)

### PR DESCRIPTION
**Pull request by chiljamgossow**
Merge Release 1.8.x in 1.9.x

Please check whether all fixes to the submission flow are included and test on the device

Specifically:

```bash
# Conflicts:
#	Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/SubmissionRepository.kt
#	Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/SubmissionCardsStateProvider.kt
#	Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/testresult/SubmissionTestResultViewModel.kt
#	Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/viewmodel/SubmissionViewModel.kt
#	Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/DataReset.kt
#	Corona-Warn-App/src/main/res/values-de/legal_strings.xml
#	Corona-Warn-App/src/test/java/de/rki/coronawarnapp/main/home/SubmissionCardsStateProviderTest.kt
```

### CODE REVIEW

**Review by janetback — APPROVED** [review]

**Review by ralfgehrer — COMMENTED** [review]
Looks good, works well on Pixel (Android 10).
Risk calculation works, as well as a positive test submission with symptoms and scanning QR codes for negative/pending tests.

**Review by ralfgehrer — APPROVED** [review]
Please do **NOT** squash merge NOR rebase this PR. Switch the setting to merge commit.

**Review by AndroidMedaGalaxy — COMMENTED** [review]
Submission Flow tested successfully   ＼(＾O＾)／

**Review by Oliver-Zimmerman — APPROVED** [review]
Submission tested, Risk calculation observed. LGTM 👍

**Pull request merged**
